image: ruby:2.7

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - pwd
    - cp -R output public
    - more input/assets/css/mitre.css >> public/assets/css/project.css
    
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


