image: ruby:2.7

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    # - pwd
    # - cp -R output public
    # - sed "s/<\!-- Placeholder for child template header declarations -->/<div id="title">Standard Patient Health Record<\/div><div id="mitre">MITRE<\/div>/" public/index.html > public/index.html
    # - sed "s/<\!-- Placeholder for child template header declarations -->/<div id="title">Standard Patient Health Record<\/div><div id="mitre">MITRE<\/div>/" public/index.html > public/index.html
    # - sed "s/<\!-- Placeholder for child template header declarations -->/<div id="title">Standard Patient Health Record<\/div><div id="mitre">MITRE<\/div>/" public/datamodel.html > public/datamodel.html
    # - sed "s/<\!-- Placeholder for child template header declarations -->/<div id="title">Standard Patient Health Record<\/div><div id="mitre">MITRE<\/div>/" public/datastorage.html > public/datastorage.html
    # - sed "s/<\!-- Placeholder for child template header declarations -->/<div id="title">Standard Patient Health Record<\/div><div id="mitre">MITRE<\/div>/" public/environments.html > public/environments.html
    # - sed "s/<\!-- Placeholder for child template header declarations -->/<div id="title">Standard Patient Health Record<\/div><div id="mitre">MITRE<\/div>/" public/functionality.html > public/functionality.html
    # - sed "s/<\!-- Placeholder for child template header declarations -->/<div id="title">Standard Patient Health Record<\/div><div id="mitre">MITRE<\/div>/" public/personas.html > public/personas.html
    # - sed "s/<\!-- Placeholder for child template header declarations -->/<div id="title">Standard Patient Health Record<\/div><div id="mitre">MITRE<\/div>/" public/physiology.html > public/physiology.html

    # - more input/assets/css/mitre.css >> public/assets/css/project.css
        
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "synthea-patients"'


