image: ruby:2.7

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - pwd
    - cp -R output public
    - echo '.table { width: 100%; }' >> public/assets/css/project.css
    - echo '.markdown-toc { width: 300px; }' >> public/assets/css/project.css
    
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'


