CodeSystem: ObservationPGHD
Id: observation-pghd-codes
Title: "Observation PGHD Codes"
Description: """
Code defining the type of PGHD data  
PGHDデータの種別を定義するコード
"""
* insert CodeSystemRules
* ^hierarchyMeaning = #grouped-by

* #Activity "Activity" ""
* #Activity #activeEnergyBurned "Active energy burned" "A quantity sample type that measures the amount of active energy the user has burned."
* #Activity #appleExerciseTime "Apple exercise time" "A quantity sample type that measures the amount of time the user spent exercising."
* #Activity #appleMoveTime "Apple move time" "A quantity sample type that measures the amount of time the user has spent performing activities that involve full-body movements during the specified day."
* #Activity #appleStandHour "Apple stand hour" "A category sample type that counts the number of hours in the day during which the user has stood and moved for at least one minute per hour."
* #Activity #appleStandTime "Apple stand time" "A quantity sample type that measures the amount of time the user has spent standing."
* #Activity #basalEnergyBurned "Basal energyBurned" "A quantity sample type that measures the resting energy burned by the user."
* #Activity #cyclingCadence "Cycling cadence" "Captures the user's cycling pedaling cadence. Each record represents a series of measurements."
* #Activity #cyclingFunctionalThresholdPower "Cycling functional threshold power" "A quantity sample type that measures the highest average power output the user can maintain for an hour."
* #Activity #cyclingPower "Cycling power" "A quantity sample type that measures power output by the user while cycling."
* #Activity #cyclingSpeed "Cycling speed" "A quantity sample type measuring the user's speed while cycling."
* #Activity #distance "Distance" "Captures distance travelled by the user since the last reading."
* #Activity #elevationGained "Elevation gained" "Captures the elevation gained by the user since the last reading."
* #Activity #totalEnergyBurned "Total energy burned" "Captures the user's steps cadence. Each record represents a series of measurements."
* #Activity #distanceCycling "Distance cycling" "A quantity sample type that measures the distance the user has moved by cycling."
* #Activity #distanceDownhillSnowSports "Distance downhill snow sports" "A quantity sample type that measures the distance the user has traveled while skiing or snowboarding."
* #Activity #distanceSwimming "Distance swimming" "A quantity sample type that measures the distance the user has moved while swimming."
* #Activity #distanceWalkingRunning "Distance walking running" "A quantity sample type that measures the distance the user has moved by walking or running."
* #Activity #distanceWheelchair "Distance wheelchair" "A quantity sample type that measures the distance the user has moved using a wheelchair."
* #Activity #flightsClimbed "Flights climbed" "A quantity sample type that measures the number flights of stairs that the user has climbed."
* #Activity #lowCardioFitnessEvent "Low cardio fitness event" "An event that indicates the user's VO2 max values consistently fall below a particular aerobic fitness threshold."
* #Activity #nikeFuel "NikeFuel" "A quantity sample type that measures the number of NikeFuel points the user has earned."
* #Activity #physicalEffort "Physical effort" "A quantity sample type that records an estimate of the energy the user using."
* #Activity #power "Power" "Captures the power generated by the user, e.g. during rowing with a power meter. Each record represents a series of measurements."
* #Activity #pushCount "Push count" "A quantity sample type that measures the number of pushes that the user has performed while using a wheelchair."
* #Activity #runningGroundContactTime "Running ground contact time" "A quantity sample type that measures the amount of time the runner's foot is in contact with the ground while running."
* #Activity #runningPower "Running power" "A quantity sample type that measures the rate of work required for the runner to maintain their speed."
* #Activity #runningSpeed "Running speed" "A quantity sample type that measures the runner's speed."
* #Activity #runningStrideLength "Running stride length" "A quantity sample type that measures the distance covered by a single step while running."
* #Activity #runningVerticalOscillation "Running vertical oscillation" "A quantity sample type measuring pelvis vertical range of motion during a single running stride."
* #Activity #stepsCadence "Steps cadence" "Captures the user's steps cadence. Each record represents a series of measurements."
* #Activity #stepCount "Step count" "A quantity sample type that measures the number of steps the user has taken."
* #Activity #speed "Speed" "Captures the user's speed, e.g. during running. Each record represents a series of measurements."
* #Activity #swimmingStrokeCount "Swimming stroke count" "A quantity sample type that measures the number of strokes performed while swimming."
* #Activity #vo2Max "VO2 max" "A quantity sample that measures the maximal oxygen consumption during exercise."
* #Activity #pace "Pace" "Pace at a specific point in time. Will be 0 if the user stops moving, otherwise the value will be in milliseconds/kilometer."
* #Activity #moderateActivity "Moderate activity" "Represents moderate (3.0-5.9 MET) activity."
* #Activity #vigorousActivity "Vigorous activity" "Represents vigorous (6.0- MET) activity."
* #Activity #moderateToVigorousActivity "Moderate to vigorous activity" "Weekly moderate to vigorous physical activity in minutes."
* #Activity #met "Met" ""
* #Activity #metByStandardRmr "Met by standard RMR" "Metabolic equivalent of task (MET) calculated based on either measured, estimated or reported exercise metabolic rate and the standard resting metabolic rate (RMR)."
* #Activity #crossCountrySkiingSpeed "Cross country skiing speed" "A quantity sample type measuring the user's speed while cross country skiing."
* #Activity #distanceCrossCountrySkiing "Distance cross country skiing" "A quantity sample type that measures the distance the user has moved while cross country skiing."
* #Activity #paddleSportsSpeed "Paddle sports speed" "A quantity sample type measuring the user's speed during paddle sports."
* #Activity #distancePaddleSports "Distance paddle sports" "A quantity sample type that measures the distance the user has moved during paddle sports."
* #Activity #rowingSpeed "Rowing speed" "A quantity sample type measuring the user's rowing speed."
* #Activity #distanceRowing "Distance rowing" "A quantity sample type measuring the distance the user has rowed."
* #Activity #distanceSkatingSports "Distance skating sports" "A quantity sample type that measures the distance the user has skated."
* #Activity #estimatedWorkoutEffortScore "Estimated workout effort score" "A quantity sample type that represents estimate of exertion score."
* #Activity #workoutEffortScore "Workout effort score" "A quantity sample type that represents exertion score."
* #AlcoholConsumption "Alcohol consumption" ""
* #AlcoholConsumption #bloodAlcoholContent "Blood alcohol content" "quantity sample type that measures the user's blood alcohol content."
* #AlcoholConsumption #numberOfAlcoholicBeverages "Number of alcoholic beverages" "A quantity sample type that measures the number of standard alcoholic drinks that the user has consumed."
* #BodyMeasurements "Body measurements" ""
* #BodyMeasurements #appleSleepingWristTemperature "Apple sleeping wrist temperature" "A quantity sample type that records the wrist temperature during sleep."
* #BodyMeasurements #bodyFatPercentage "Body fat percentage" "A quantity sample type that measures the user's body fat percentage."
* #BodyMeasurements #bodyMass "Body mass" "A quantity sample type that measures the user's weight."
* #BodyMeasurements #bodyMassIndex "Body mass index" "A quantity sample type that measures the user's body mass index."
* #BodyMeasurements #height "Height" "A quantity sample type that measures the user's height."
* #BodyMeasurements #hipCircumference "Hip circumference" "A quantity sample type that measures the user's hip circumference."
* #BodyMeasurements #leanBodyMass "Lean body mass" "A quantity sample type that measures the user's lean body mass."
* #BodyMeasurements #waistCircumference "Waist circumference" "A quantity sample type that measures the user's waist circumference."
* #BodyMeasurements #boneMass "Bone mass" "A quantity sample type that measures the user's bone mass"
* #Diving "Diving" ""
* #Diving #underwaterDepth "Underwater depth" "A quantity sample that records a person's depth underwater."
* #Diving #waterTemperature "Water temperature" "A quantity sample that records the water temperature."
* #Hearing "Hearing" ""
* #Hearing #environmentalAudioExposure "Environmental audio exposure" "A quantity sample type that measures audio exposure to sounds in the environment."
* #Hearing #environmentalAudioExposureEvent "Environmental audio exposure event" "A category sample type that records exposure to potentially damaging sounds from the environment."
* #Hearing #environmentalSoundReduction "Environmental sound reduction" "The environmental sound level reduced while user wearing AirPods Pro and using Active Noise Cancellation or Adaptive Transparency mode."
* #Hearing #headphoneAudioExposure "Headphone audio exposure" "A quantity sample type that measures audio exposure from headphones."
* #Hearing #headphoneAudioExposureEvent "Headphone audio exposure event" "A category sample type that records exposure to potentially damaging sounds from headphones."
* #Heart "Heart" ""
* #Heart #electrocardiogram "Electrocardiogram" "A type that identifies samples containing electrocardiogram data."
* #Heart #heartBeatSeries "Heart beat series" "A series sample containing heartbeat data."
* #LabAndTestResults "Lab and test results" ""
* #LabAndTestResults #bloodGlucose "Blood glucose" "A quantity sample type that measures the user's blood glucose level."
* #LabAndTestResults #electrodermalActivity "Electrodermal activity" "A quantity sample type that measures electrodermal activity."
* #LabAndTestResults #forcedExpiratoryVolume1 "Forced expiratory volume1" "A quantity sample type that measures the amount of air that can be forcibly exhaled from the lungs during the first second of a forced exhalation."
* #LabAndTestResults #forcedVitalCapacity "Forced vital capacity" "A quantity sample type that measures the amount of air that can be forcibly exhaled from the lungs after taking the deepest breath possible."
* #LabAndTestResults #inhalerUsage "Inhaler usage" "A quantity sample type that measures the number of puffs the user takes from their inhaler."
* #LabAndTestResults #insulinDelivery "Insulin delivery" "A quantity sample that measures the amount of insulin delivered."
* #LabAndTestResults #numberOfTimesFallen "Number of times fallen" "A quantity sample type that measures the number of times the user fell."
* #LabAndTestResults #peakExpiratoryFlowRate "Peak expiratory flow rate" "A quantity sample type that measures the user's maximum flow rate generated during a forceful exhalation."
* #LabAndTestResults #peripheralPerfusionIndex "Peripheral perfusion index" "A quantity sample type that measures the user's peripheral perfusion index."
* #LabAndTestResults #timeInDaylight "Time in daylight" "A quantity sample type that captures the amount of time the user spent in daylight."
* #LabAndTestResults #inspiratoryTime "Inspiratory time" "The duration of a person's inspiration, either a single measurement, or the result of aggregating several measurements made over time."
* #LabAndTestResults #ventilationCycleTime "Ventilation cycle time" "Represents the duration of a person's complete respiration."
* #LabAndTestResults #minuteVolume "Minute volume" "The volume of gas inhaled or exhaled from a person's lungs per minute."
* #LabAndTestResults #breathCarbonMonoxide "Breath carbon monoxide" "The amount of carbon monoxide gas present in a person's exhaled breath."
* #Mindfulness "Mindfulness" ""
* #Mindfulness #mindfulSession "Mindful session" "A category sample type for recording a mindful session."
* #Sleep "Sleep" ""
* #Sleep #sleepAnalysis "Sleep analysis" "A category sample type for sleep analysis information."
* #Sleep #sleepEpisode "Sleep episode" "Represents one sleep episode, which can be the main sleep event (i.e., a night sleep for most people) or a nap."
* #Sleep #snoreIndex "Snore index" "The number of snore events per hour."
* #Sleep #snoreEvent "Snore event" "A data type that represents the loudness, duration of snoring, and the posture during snoring."
* #Sleep #sleepAHI "Sleep ahi" "The number of apnea and hypopnea events recorded per hour of sleep."
* #Sleep #sleepArousalIndex "Sleep arousal index" "The average number of arousals per hour of sleep."
* #Sleep #appleSleepingBreathingDisturbances "Apple sleeping breathing disturbances" "A quantity sample type that measures a nightly breathing disturbances."
* #Sleep #sleepApneaEvent "Sleep apnea event" "A category type that represents sleep apnea event."
* #Mobility "Mobility" ""
* #Mobility #appleWalkingSteadiness "Apple walking steadiness" "A quantity sample type that measures the steadiness of the user's gait."
* #Mobility #appleWalkingSteadinessEvent "Apple walking steadiness event" "A category sample type that records an incident where the user showed a reduced score for their gait's steadiness."
* #Mobility #sixMinuteWalkTestDistance "Six minute walk test distance" "A quantity sample type that stores the distance a user can walk during a six-minute walk test."
* #Mobility #walkingSpeed "Walking speed" "A quantity sample type that measures the user's average speed when walking steadily over flat ground."
* #Mobility #walkingStepLength "Walking step length" "A quantity sample type that measures the average length of the user's step when walking steadily over flat ground."
* #Mobility #walkingAsymmetryPercentage "Walking asymmetry percentage" "A quantity sample type that measures the percentage of steps in which one foot moves at a different speed than the other when walking on flat ground."
* #Mobility #walkingDoubleSupportPercentage "Walking double support percentage" "A quantity sample type that measures the percentage of time when both of the user's feet touch the ground while walking steadily over flat ground."
* #Mobility #stairAscentSpeed "Stair ascent speed" "A quantity sample type measuring the user's speed while climbing a flight of stairs."
* #Mobility #stairDescentSpeed "Stair descent speed" "A quantity sample type measuring the user's speed while descending a flight of stairs."
* #Nutrition "Nutrition" ""
* #Nutrition #dietaryBiotin "Biotin" "A quantity sample type that measures the amount of biotin (vitamin B7) consumed."
* #Nutrition #dietaryCaffeine "Caffeine" "A quantity sample type that measures the amount of caffeine consumed."
* #Nutrition #dietaryCalcium "Calcium" "A quantity sample type that measures the amount of calcium consumed."
* #Nutrition #dietaryCarbohydrates "Carbohydrates" "A quantity sample type that measures the amount of carbohydrates consumed."
* #Nutrition #dietaryChloride "Chloride" "A quantity sample type that measures the amount of chloride consumed."
* #Nutrition #dietaryCholesterol "Cholesterol" "A quantity sample type that measures the amount of cholesterol consumed."
* #Nutrition #dietaryChromium "Chromium" "A quantity sample type that measures the amount of chromium consumed."
* #Nutrition #dietaryCopper "Copper" "A quantity sample type that measures the amount of copper consumed."
* #Nutrition #dietaryEnergyConsumed "Energy consumed" "A quantity sample type that measures the amount of energy consumed."
* #Nutrition #dietaryEnergyFromFat "Energy from fat" "A quantity sample type that measures the amount of energy form fat."
* #Nutrition #dietaryFatMonounsaturated "Fat monounsaturated" "A quantity sample type that measures the amount of monounsaturated fat consumed."
* #Nutrition #dietaryFatPolyunsaturated "Fat polyunsaturated" "A quantity sample type that measures the amount of polyunsaturated fat consumed."
* #Nutrition #dietaryFatUnsaturated "Fat unsaturated" "A quantity sample type that measures the amount of unsaturated fat consumed."
* #Nutrition #dietaryTransFat "Trans fat" "A quantity sample type that measures the amount of trans fat consumed."
* #Nutrition #dietaryFatSaturated "Fat saturated" "A quantity sample type that measures the amount of saturated fat consumed."
* #Nutrition #dietaryFatTotal "Fat total" "A quantity sample type that measures the total amount of fat consumed."
* #Nutrition #dietaryFiber "Fiber" "A quantity sample type that measures the amount of fiber consumed."
* #Nutrition #dietaryFolateOrFolicAcid "Folate or folic acid" "A quantity sample type that measures the amount of folate (folic acid) consumed."
* #Nutrition #dietaryFolate "Folate" "A quantity sample type that measures the amount of folate consumed."
* #Nutrition #dietaryFolicAcid "Folic acid" "A quantity sample type that measures the amount of folic acid consumed."
* #Nutrition #dietaryIodine "Iodine" "A quantity sample type that measures the amount of iodine consumed."
* #Nutrition #dietaryIron "Iron" "A quantity sample type that measures the amount of iron consumed."
* #Nutrition #dietaryMagnesium "Magnesium" "A quantity sample type that measures the amount of magnesium consumed."
* #Nutrition #dietaryManganese "Manganese" "A quantity sample type that measures the amount of manganese consumed."
* #Nutrition #dietaryMolybdenum "Molybdenum" "A quantity sample type that measures the amount of molybdenum consumed."
* #Nutrition #dietaryNiacin "Niacin" "A quantity sample type that measures the amount of niacin (vitamin B3) consumed."
* #Nutrition #dietaryPantothenicAcid "Pantothenic acid" "A quantity sample type that measures the amount of pantothenic acid (vitamin B5) consumed."
* #Nutrition #dietaryPhosphorus "Phosphorus" "A quantity sample type that measures the amount of phosphorus consumed."
* #Nutrition #dietaryPotassium "Potassium" "A quantity sample type that measures the amount of potassium consumed."
* #Nutrition #dietaryProtein "Protein" "A quantity sample type that measures the amount of protein consumed."
* #Nutrition #dietaryRiboflavin "Riboflavin" "A quantity sample type that measures the amount of riboflavin (vitamin B2) consumed."
* #Nutrition #dietarySelenium "Selenium" "A quantity sample type that measures the amount of selenium consumed."
* #Nutrition #dietarySodium "Sodium" "A quantity sample type that measures the amount of sodium consumed."
* #Nutrition #dietarySugar "Sugar" "A quantity sample type that measures the amount of sugar consumed."
* #Nutrition #dietaryThiamin "Thiamin" "A quantity sample type that measures the amount of thiamin (vitamin B1) consumed."
* #Nutrition #dietaryVitaminA "Vitamin a" "A quantity sample type that measures the amount of vitamin A consumed."
* #Nutrition #dietaryVitaminB12 "Dietary vitamin b12" "A quantity sample type that measures the amount of cyanocobalamin (vitamin B12) consumed."
* #Nutrition #dietaryVitaminB6 "Vitamin b6" "A quantity sample type that measures the amount of pyridoxine (vitamin B6) consumed."
* #Nutrition #dietaryVitaminC "Vitamin c" "A quantity sample type that measures the amount of vitamin C consumed."
* #Nutrition #dietaryVitaminD "Vitamin d" "A quantity sample type that measures the amount of vitamin D consumed."
* #Nutrition #dietaryVitaminE "Vitamin e" "A quantity sample type that measures the amount of vitamin E consumed."
* #Nutrition #dietaryVitaminK "Vitamin k" "A quantity sample type that measures the amount of vitamin K consumed."
* #Nutrition #dietaryWater "Water" "A quantity sample type that measures the amount of water consumed."
* #Nutrition #dietaryZinc "Zinc" "A quantity sample type that measures the amount of zinc consumed."
* #ReproductiveHealth "Reproductive health" ""
* #ReproductiveHealth #basalBodyTemperature "Basal body temperature" "A quantity sample type that records the user's basal body temperature."
* #ReproductiveHealth #cervicalMucusQuality "Cervical mucus quality" "A category sample type that records the quality of the user's cervical mucus."
* #ReproductiveHealth #contraceptive "Contraceptive" "A category sample type that records the use of contraceptives."
* #ReproductiveHealth #intermenstrualBleeding "Intermenstrual bleeding" "A category sample type that records spotting outside the normal menstruation period."
* #ReproductiveHealth #irregularMenstrualCycles "Irregular menstrual cycles" "A category sample that indicates an irregular menstrual cycle."
* #ReproductiveHealth #infrequentMenstrualCycles "Infrequent menstrual cycles" "A category sample that indicates an infrequent menstrual cycle."
* #ReproductiveHealth #lactation "Lactation" "A category type that records lactation."
* #ReproductiveHealth #menstrualFlow "Menstrual flow" "A category sample type that records menstrual cycles."
* #ReproductiveHealth #menstrualPeriod "Menstrual period" "A category sample type that records menstrual periods."
* #ReproductiveHealth #ovulationTestResult "Ovulation test result" "A category sample type that records the result of an ovulation home test."
* #ReproductiveHealth #persistentIntermenstrualBleeding "Persistent intermenstrual bleeding" "A category sample that indicates persistent intermenstrual bleeding."
* #ReproductiveHealth #pregnancy "Pregnancy" "A category type that records pregnancy."
* #ReproductiveHealth #pregnancyTestResult "Pregnancy test result" "A category type that represents the results from a home pregnancy test."
* #ReproductiveHealth #progesteroneTestResult "Progesterone test result" "A category type that represents the results from a home progesterone test."
* #ReproductiveHealth #prolongedMenstrualPeriods "Prolonged menstrual periods" "A category sample that indicates a prolonged menstrual cycle."
* #ReproductiveHealth #sexualActivity "Sexual activity" "A category sample type that records sexual activity."
* #ReproductiveHealth #bleedingAfterPregnancy "Bleeding after pregnancy" "A category type that represents bleeding after pregnancy."
* #ReproductiveHealth #bleedingDuringPregnancy "Bleeding during pregnancy" "A category type that represents bleeding during pregnancy."
* #SelfCare "Self care" ""
* #SelfCare #handwashingEvent "Handwashing event" "A category sample type for handwashing events."
* #SelfCare #toothbrushingEvent "Toothbrushing event" "A category sample type for toothbrushing events."
* #Symptom "Symptom" ""
* #Symptom #abdominalCramps "Bdominal cramps" "A category type that records abdominal cramps as a symptom."
* #Symptom #acne "Acne" "A category type that records acne as a symptom."
* #Symptom #appetiteChanges "Appetite changes" "A category type that records changes in appetite as a symptom."
* #Symptom #bladderIncontinence "Bladder incontinence" "A category type that records bladder incontinence as a symptom."
* #Symptom #bloating "Bloating" "A category type that records bloating as a symptom."
* #Symptom #breastPain "Breast pain" "A category type that records breast pain as a symptom."
* #Symptom #chestTightnessOrPain "Chest tightness or pain" "A category type that records chest tightness or pain as a symptom."
* #Symptom #chills "Chills" "A category type that records chills as a symptom."
* #Symptom #constipation "Constipation" "A category type that records constipation as a symptom."
* #Symptom #coughing "Coughing" "A category type that records coughing as a symptom."
* #Symptom #diarrhea "Diarrhea" "A category type that records diarrhea as a symptom."
* #Symptom #dizziness "Dizziness" "A category type that records dizziness as a symptom."
* #Symptom #drySkin "Dry skin" "A category type that records dry skin as a symptom."
* #Symptom #fainting "Fainting" "A category type that records fainting as a symptom."
* #Symptom #fatigue "Fatigue" "A category type that records fatigue as a symptom."
* #Symptom #fever "Fever" "A category type that records fever as a symptom."
* #Symptom #generalizedBodyAche "Generalized body ache" "A category type that records body ache as a symptom."
* #Symptom #hairLoss "Hair loss" "A category type that records hair loss as a symptom."
* #Symptom #headache "Headache" "A category type that records headache as a symptom."
* #Symptom #heartburn "Heartburn" "A category type that records heartburn as a symptom."
* #Symptom #hotFlashes "Hot flashes" "A category type that records hot flashes as a symptom."
* #Symptom #lossOfSmell "Loss of smell" "A category type that records loss of smell as a symptom."
* #Symptom #lossOfTaste "Loss of taste" "A category type that records loss of taste as a symptom."
* #Symptom #lowerBackPain "Lower back pain" "A category type that records lower back pain as a symptom."
* #Symptom #memoryLapse "Memory lapse" "A category type that records memory lapse as a symptom."
* #Symptom #moodChanges "Mood changes" "A category type that records mood changes as a symptom."
* #Symptom #nausea "Nausea" "A category type that records nausea as a symptom."
* #Symptom #nightSweats "Night sweats" "A category type that records night sweats as a symptom."
* #Symptom #pelvicPain "Pelvic pain" "A category type that records pelvic pain as a symptom."
* #Symptom #rapidPoundingOrFlutteringHeartbeat "Rapid pounding or fluttering heartbeat" "A category type that records a rapid,  pounding,  or fluttering heartbeat as a symptom."
* #Symptom #runnyNose "Runny nose" "A category type that records runny nose as a symptom."
* #Symptom #shortnessOfBreath "Shortness of breath" "A category type that records shortness of breath as a symptom."
* #Symptom #sinusCongestion "Sinus congestion" "A category type that records sinus congestion as a symptom."
* #Symptom #skippedHeartbeat "Skipped heartbeat" "A category type that records skipped heartbeat as a symptom."
* #Symptom #sleepChanges "Sleep changes" "A category type that records sleep changes as a symptom."
* #Symptom #soreThroat "Sore throat" "A category type that records sore throat as a symptom."
* #Symptom #vaginalDryness "Vaginal dryness" "A category type that records vaginal dryness as a symptom."
* #Symptom #vomiting "Vomiting" "A category type that records vomiting as a symptom."
* #Symptom #wheezing "Wheezing" "A category type that records wheezing as a symptom."
* #UVExposure "Uv exposure" ""
* #UVExposure #uvExposure "Uv exposure" "A quantity sample type that measures the user's exposure to UV radiation."
* #VitalSigns "Vital signs" ""
* #VitalSigns #atrialFibrillationBurden "Atrial fibrillation burden" "A quantity type that measures an estimate of the percentage of time a person's heart shows signs of atrial fibrillation (AFib) while wearing Apple Watch."
* #VitalSigns #bloodPressure "Blood pressure" "A correlation sample that combines a systolic sample and a diastolic sample into a single blood pressure reading."
* #VitalSigns #bloodPressureDiastolic "Blood pressure diastolic" "A quantity sample type that measures the user's diastolic blood pressure."
* #VitalSigns #bloodPressureSystolic "Blood pressure systolic" "A quantity sample type that measures the user's systolic blood pressure."
* #VitalSigns #bodyTemperature "Body temperature" "A quantity sample type that measures the user's body temperature."
* #VitalSigns #heartRate "Heart rate" "A quantity sample type that measures the user's heart rate."
* #VitalSigns #heartRateVariabilitySDNN "Heart rate variability sdnn" "A quantity sample type that measures the standard deviation of heartbeat intervals."
* #VitalSigns #heartRateRecoveryOneMinute "Heart rate recovery one minute" "A quantity sample that records the reduction in heart rate from the peak exercise rate to the rate one minute after exercising ended."
* #VitalSigns #highHeartRateEvent "High heart rate event" "A category sample type for high heart rate events."
* #VitalSigns #irregularHeartRhythmEvent "Irregular heart rhythm event" "A category sample type for irregular heart rhythm events."
* #VitalSigns #lowHeartRateEvent "Low heart rate event" "A category sample type for low heart rate events."
* #VitalSigns #oxygenSaturation "Oxygen saturation" "A quantity sample type that measures the user's oxygen saturation."
* #VitalSigns #respiratoryRate "Respiratory rate" "A quantity sample type that measures the user's respiratory rate."
* #VitalSigns #restingHeartRate "Resting heart rate" "A quantity sample type that measures the user's resting heart rate."
* #VitalSigns #walkingHeartRateAverage "Walking heart rate average" "A quantity sample type that measures the user's heart rate while walking."
* #VitalSigns #rrInterval "Rr interval" "The time period between successive R waves."
* #WorkoutActivity "Workout activity" ""
* #WorkoutActivity #americanFootball "American football" "The constant for playing American football."
* #WorkoutActivity #archery "Archery" "The constant for shooting archery."
* #WorkoutActivity #australianFootball "Australian football" "The constant for playing Australian football."
* #WorkoutActivity #badminton "Badminton" "The constant for playing badminton."
* #WorkoutActivity #barre "Barre" "The constant for barre workout."
* #WorkoutActivity #baseball "Baseball" "The constant for playing baseball."
* #WorkoutActivity #basketball "Basketball" "The constant for playing basketball."
* #WorkoutActivity #bowling "Bowling" "The constant for bowling."
* #WorkoutActivity #boxing "Boxing" "The constant for boxing."
* #WorkoutActivity #cardioDance "Cardio dance" "The constant for cardiovascular dance workouts."
* #WorkoutActivity #climbing "Climbing" "The constant for climbing."
* #WorkoutActivity #cooldown "Cooldown" "The constant for low intensity stretching and mobility exercises following a more vigorous workout."
* #WorkoutActivity #coreTraining "Core training" "The constant for core training."
* #WorkoutActivity #cricket "Cricket" "The constant for playing cricket."
* #WorkoutActivity #crossCountrySkiing "Cross country skiing" "The constant for cross country skiing."
* #WorkoutActivity #crossTraining "Cross training" "The constant for exercise that includes any mixture of cardio, strength, and/or flexibility training."
* #WorkoutActivity #curling "Curling" "The constant for curling."
* #WorkoutActivity #cycling "Cycling" "The constant for cycling."
* #WorkoutActivity #dance "Dance" "(Deprecated) The constant for dancing."
* #WorkoutActivity #danceInspiredTraining "Dance inspired training" "(Deprecated) The constant for workouts inspired by dance, including Pilates, Barre, and Feldenkrais."
* #WorkoutActivity #discSports "Disc sports" "The constant for playing disc sports such as Ultimate and Disc Golf."
* #WorkoutActivity #downhillSkiing "Downhill skiing" "The constant for downhill skiing."
* #WorkoutActivity #elliptical "Elliptical" "The constant for workouts on an elliptical machine."
* #WorkoutActivity #equestrianSports "Equestrian sports" "The constant for activities that involve riding a horse, including polo, horse racing, and horse riding."
* #WorkoutActivity #fencing "Fencing" "The constant for fencing."
* #WorkoutActivity #fishing "Fishing" "The constant for fishing."
* #WorkoutActivity #fitnessGaming "Fitness gaming" "The constant for playing fitness-based video games."
* #WorkoutActivity #flexibility "Flexibility" "The constant for a flexibility workout."
* #WorkoutActivity #functionalStrengthTraining "Functional strength training" "The constant for strength training, primarily with free weights and body weight."
* #WorkoutActivity #golf "Golf" "The constant for playing golf."
* #WorkoutActivity #gymnastics "Gymnastics" "Performing gymnastics."
* #WorkoutActivity #handball "Handball" "The constant for playing handball."
* #WorkoutActivity #handCycling "Hand cycling" "The constant for hand cycling."
* #WorkoutActivity #highIntensityIntervalTraining "High intensity interval training" "The constant for high intensity interval training."
* #WorkoutActivity #hiking "Hiking" "The constant for hiking."
* #WorkoutActivity #hockey "Hockey" "The constant for playing hockey, including ice hockey, field hockey, and related sports."
* #WorkoutActivity #hunting "Hunting" "The constant for hunting."
* #WorkoutActivity #jumpRope "Jump rope" "The constant for jumping rope."
* #WorkoutActivity #kickboxing "Kickboxing" "The constant for kickboxing."
* #WorkoutActivity #lacrosse "Lacrosse" "The constant for playing lacrosse."
* #WorkoutActivity #martialArts "Martial arts" "The constant for practicing martial arts."
* #WorkoutActivity #mindAndBody "Mind and body" "The constant for performing activities like walking meditation, Gyrotonic exercise, and Qigong."
* #WorkoutActivity #mixedCardio "Mixed cardio" "The constant for workouts that mix a variety of cardio exercise machines or modalities."
* #WorkoutActivity #mixedMetabolicCardioTraining "Mixed metabolic cardio training" "The constant for performing any mix of cardio-focused exercises."
* #WorkoutActivity #other "Other" "The constant for a workout that does not match any of the other workout activity types."
* #WorkoutActivity #paddleSports "Paddle sports" "The constant for canoeing, kayaking, paddling an outrigger, paddling a stand-up paddle board, and related sports."
* #WorkoutActivity #pickleball "Pickleball" "The constant for playing pickleball."
* #WorkoutActivity #pilates "Pilates" "The constant for a pilates workout."
* #WorkoutActivity #play "Play" "The constant for play-based activities like tag, dodgeball, hopscotch, tetherball, and playing on a jungle gym."
* #WorkoutActivity #preparationAndRecovery "Preparation and recovery" "The constant for warm-up and therapeutic activities like foam rolling and stretching."
* #WorkoutActivity #racquetball "Racquetball" "The constant for playing racquetball."
* #WorkoutActivity #rowing "Rowing" "The constant for rowing."
* #WorkoutActivity #rugby "Rugby" "The constant for playing rugby."
* #WorkoutActivity #running "Running" "The constant for running and jogging."
* #WorkoutActivity #sailing "Sailing" "The constant for sailing."
* #WorkoutActivity #skatingSports "Skating sports" "The constant for skating activities, including ice skating, speed skating, inline skating, and skateboarding."
* #WorkoutActivity #snowboarding "Snowboarding" "The constant for snowboarding."
* #WorkoutActivity #snowSports "Snow sports" "The constant for a variety of snow sports, including sledding, snowmobiling, or building a snowman."
* #WorkoutActivity #soccer "Soccer" "The constant for playing soccer."
* #WorkoutActivity #socialDance "Social dance" "The constant for dancing with a partner or partners, such as swing, salsa, or folk dances."
* #WorkoutActivity #softball "Softball" "The constant for playing softball."
* #WorkoutActivity #squash "Squash" "The constant for playing squash."
* #WorkoutActivity #stairClimbing "Stair climbing" "The constant for workouts using a stair climbing machine."
* #WorkoutActivity #stairs "Stairs" "The constant for running, walking, or other drills using stairs (for example, in a stadium or inside a multilevel building)."
* #WorkoutActivity #stepTraining "Step training" "The constant for training using a step bench."
* #WorkoutActivity #surfingSports "Surfing sports" "The constant for a variety of surf sports, including surfing, kite surfing, and wind surfing."
* #WorkoutActivity #swimBikeRun "Swim bike run" "The constant for multisport activities like triathlons."
* #WorkoutActivity #swimming "Swimming" "The constant for swimming."
* #WorkoutActivity #tableTennis "Table tennis" "The constant for playing table tennis."
* #WorkoutActivity #taiChi "Tai chi" "The constant for tai chi."
* #WorkoutActivity #tennis "Tennis" "The constant for playing tennis."
* #WorkoutActivity #trackAndField "Track and field" "Participating in track and field events, including shot put, javelin, pole vaulting, and related sports."
* #WorkoutActivity #traditionalStrengthTraining "Traditional strength training" "The constant for strength training exercises primarily using machines or free weights."
* #WorkoutActivity #transition "Transition" "A constant for the transition time between activities in a multisport workout."
* #WorkoutActivity #underwaterDiving "Underwater diving" "The constant for underwater diving."
* #WorkoutActivity #volleyball "Volleyball" "The constant for playing volleyball."
* #WorkoutActivity #walking "Walking" "The constant for walking."
* #WorkoutActivity #waterFitness "Water fitness" "The constant for aerobic exercise performed in shallow water."
* #WorkoutActivity #waterPolo "Water polo" "The constant for playing water polo."
* #WorkoutActivity #waterSports "Water sports" "The constant for a variety of water sports, including water skiing, wake boarding, and related activities."
* #WorkoutActivity #wheelchairRunPace "Wheelchair run pace" "The constant for wheelchair workout at running pace."
* #WorkoutActivity #wheelchairWalkPace "Wheelchair walk pace" "The constant for a wheelchair workout at walking pace."
* #WorkoutActivity #wrestling "Wrestling" "The constant for wrestling."
* #WorkoutActivity #yoga "Yoga" "The constant for practicing yoga."
* #WorkoutActivity #backExtension "Back extension" "The constant for back Extension."
* #WorkoutActivity #barbellShoulderPress "Barbell shoulder press" "The constant for barbell shoulder press."
* #WorkoutActivity #benchPress "Bench press" "The constant for bench press."
* #WorkoutActivity #benchSitUp "Bench sit up" "The constant for bench sit up."
* #WorkoutActivity #biking "Biking" "The constant for biking."
* #WorkoutActivity #bikingStationary "Biking stationary" "The constant for biking stationary."
* #WorkoutActivity #bootCamp "Boot camp" "The constant for boot camp."
* #WorkoutActivity #burpee "Burpee" "The constant for burpee."
* #WorkoutActivity #calisthenics "Calisthenics" "The constant for calisthenics."
* #WorkoutActivity #crunch "Crunch" "The constant for crunch."
* #WorkoutActivity #deadlift "Deadlift" "The constant for deadlift."
* #WorkoutActivity #dumbbellCurlLeftArm "Dumbbell curl left arm" "The constant for dumbbell curl left arm."
* #WorkoutActivity #dumbbellCurlRightArm "Dumbbell curl right arm" "The constant for dumbbell curl right arm."
* #WorkoutActivity #dumbbellFrontRaise "Dumbbell front raise" "The constant for dumbbell front raise."
* #WorkoutActivity #dumbbellLateralRaise "Dumbbell lateral raise" "The constant for dumbbell lateral raise."
* #WorkoutActivity #dumbbellTricepsExtensionLeftArm "Dumbbell triceps extension left arm" "The constant for dumbbell triceps extension left arm."
* #WorkoutActivity #dumbbellTricepsExtensionRightArm "Dumbbell triceps extension right arm" "The constant for dumbbell triceps extension right arm."
* #WorkoutActivity #dumbbellTricepsExtensionTwoArm "Dumbbell triceps extension two arm" "The constant for dumbbell triceps extension two arm."
* #WorkoutActivity #exerciseClass "Exercise class" "The constant for exercise class."
* #WorkoutActivity #forwardTwist "Forward twist" "The constant for forward twist."
* #WorkoutActivity #frisbeeDisc "Frisbee disc" "The constant for frisbee disc."
* #WorkoutActivity #guidedBreathing "Guided breathing" "The constant for guided breathing."
* #WorkoutActivity #iceHockey "Ice hockey" "The constant for ice hockey."
* #WorkoutActivity #iceSkating "Ice skating" "The constant for ice skating."
* #WorkoutActivity #jumpingJack "Jumping jack" "The constant for jumping jack."
* #WorkoutActivity #latPullDown "Lat pull down" "The constant for lat pull down."
* #WorkoutActivity #lunge "Lunge" "The constant for lunge."
* #WorkoutActivity #meditation "Meditation" "The constant for meditation."
* #WorkoutActivity #paraGliding "Para gliding" "The constant for para gliding."
* #WorkoutActivity #plank "Plank" "The constant for plank."
* #WorkoutActivity #rockClimbing "Rock climbing" "The constant for rock climbing."
* #WorkoutActivity #rollerHockey "Roller hockey" "The constant for roller hockey."
* #WorkoutActivity #rowingMachine "Rowing machine" "The constant for rowing machine."
* #WorkoutActivity #runningTreadmill "Running treadmill" "The constant for running treadmill."
* #WorkoutActivity #scubaDiving "Scuba diving" "The constant for scuba diving."
* #WorkoutActivity #skiing "Skiing" "The constant for skiing."
* #WorkoutActivity #snowshoeing "Snowshoeing" "The constant for snowshoeing."
* #WorkoutActivity #squat "Squat" "The constant for squat."
* #WorkoutActivity #strengthTraining "Strength training" "The constant for strength training."
* #WorkoutActivity #stretching "Stretching" "The constant for stretching."
* #WorkoutActivity #swimmingOpenWater "Swimming open water" "The constant for swimming open water."
* #WorkoutActivity #swimmingPool "Swimming pool" "The constant for swimming pool."
* #WorkoutActivity #upperTwist "Upper twist" "The constant for upper twist."
* #WorkoutActivity #weightlifting "Weightlifting" "The constant for weightlifting."
* #WorkoutActivity #wheelchair "Wheelchair" "The constant for wheelchair."
* #WorkoutActivity #workout "Workout" "The constant for workout."
* #Audiogram "Audiogram" ""
* #Audiogram #hearingSensitivity "Hearing sensitivity" "A pair of frequencies and left/right ear sensitivity data to represent the patient's hearing sensitivity for each frequency."
* #food "Food" ""
* #medicationAdherence "Medication adherence" "The degree to which a patient correctly follows medical advice, particularly in relation to taking prescribed medication."
* #Mind "Mind" ""
* #Mind #stateOfMind "State of Mind" "Momentary emotions and daily moods."
* #Mind #gad7 "GAD-7 assessment" "The Generalized Anxiety Disorder 7-item scale."
* #Mind #phq9 "PHQ-9 assessment" "The nine-item Patient Health Questionnaire."

* insert CodeDesignationRules(#Activity, アクティビティ)
* insert CodeDesignationRules(#Activity #activeEnergyBurned,ムーブ (アクティブエネルギー\))
* insert CodeDesignationRules(#Activity #appleExerciseTime,エクササイズ時間)
* insert CodeDesignationRules(#Activity #appleMoveTime,ムーブ時間)
* insert CodeDesignationRules(#Activity #appleStandHour,スタンド)
* insert CodeDesignationRules(#Activity #appleStandTime,スタンド時間)
* insert CodeDesignationRules(#Activity #basalEnergyBurned,安静時消費エネルギー)
* insert CodeDesignationRules(#Activity #cyclingCadence,サイクリングケイデンス)
* insert CodeDesignationRules(#Activity #cyclingFunctionalThresholdPower,機能的作業閾値サイクリングパワー)
* insert CodeDesignationRules(#Activity #cyclingPower,サイクリングパワー)
* insert CodeDesignationRules(#Activity #cyclingSpeed,サイクリング速度)
* insert CodeDesignationRules(#Activity #distance,距離)
* insert CodeDesignationRules(#Activity #elevationGained,標高)
* insert CodeDesignationRules(#Activity #totalEnergyBurned,総エネルギー)
* insert CodeDesignationRules(#Activity #distanceCycling,自転車の走行距離)
* insert CodeDesignationRules(#Activity #distanceDownhillSnowSports,ダウンヒル・スノースポーツの距離)
* insert CodeDesignationRules(#Activity #distanceSwimming,泳いだ距離)
* insert CodeDesignationRules(#Activity #distanceWalkingRunning,ウォーキング＋ランニングの距離)
* insert CodeDesignationRules(#Activity #distanceWheelchair,車椅子の走行距離)
* insert CodeDesignationRules(#Activity #flightsClimbed,登った階数)
* insert CodeDesignationRules(#Activity #lowCardioFitnessEvent,心肺機能レベルの低下)
* insert CodeDesignationRules(#Activity #nikeFuel,NikeFuel)
* insert CodeDesignationRules(#Activity #physicalEffort,身体エフォート)
* insert CodeDesignationRules(#Activity #power,パワー)
* insert CodeDesignationRules(#Activity #pushCount,車椅子のプッシュ)
* insert CodeDesignationRules(#Activity #runningGroundContactTime,接地時間)
* insert CodeDesignationRules(#Activity #runningPower,ランニングパワー)
* insert CodeDesignationRules(#Activity #runningSpeed,ランニング速度)
* insert CodeDesignationRules(#Activity #runningStrideLength,ランニングの歩幅の長さ)
* insert CodeDesignationRules(#Activity #runningVerticalOscillation,上下動)
* insert CodeDesignationRules(#Activity #stepsCadence,歩行周期)
* insert CodeDesignationRules(#Activity #stepCount,歩数)
* insert CodeDesignationRules(#Activity #speed,速度)
* insert CodeDesignationRules(#Activity #swimmingStrokeCount,水泳のストローク数)
* insert CodeDesignationRules(#Activity #vo2Max,心肺機能 (VO2 max\))
* insert CodeDesignationRules(#Activity #pace,ペース)
* insert CodeDesignationRules(#Activity #moderateActivity,中強度の運動)
* insert CodeDesignationRules(#Activity #vigorousActivity,高強度の運動)
* insert CodeDesignationRules(#Activity #moderateToVigorousActivity,中から高強度の運動) 
* insert CodeDesignationRules(#Activity #met,メッツ)
* insert CodeDesignationRules(#Activity #metByStandardRmr,エネルギー代謝率に基づくメッツ)
* insert CodeDesignationRules(#Activity #crossCountrySkiingSpeed,クロスカントリースキーの速度)
* insert CodeDesignationRules(#Activity #distanceCrossCountrySkiing,クロスカントリースキーの距離)
* insert CodeDesignationRules(#Activity #paddleSportsSpeed,パドルスポーツの速度)
* insert CodeDesignationRules(#Activity #distancePaddleSports,パドルスポーツの距離)
* insert CodeDesignationRules(#Activity #rowingSpeed,ローイングの速度)
* insert CodeDesignationRules(#Activity #distanceRowing,ローイングの距離)
* insert CodeDesignationRules(#Activity #distanceSkatingSports,スケーティングスポーツの距離)
* insert CodeDesignationRules(#Activity #estimatedWorkoutEffortScore,推定ワークアウト難易度スコア)
* insert CodeDesignationRules(#Activity #workoutEffortScore,ワークアウト難易度スコア)
* insert CodeDesignationRules(#AlcoholConsumption,飲酒)
* insert CodeDesignationRules(#AlcoholConsumption #bloodAlcoholContent,血中アルコール濃度)
* insert CodeDesignationRules(#AlcoholConsumption #numberOfAlcoholicBeverages,飲酒量)
* insert CodeDesignationRules(#BodyMeasurements,身体測定値)
* insert CodeDesignationRules(#BodyMeasurements #appleSleepingWristTemperature,手首体温)
* insert CodeDesignationRules(#BodyMeasurements #bodyFatPercentage,体脂肪率)
* insert CodeDesignationRules(#BodyMeasurements #bodyMass,体重)
* insert CodeDesignationRules(#BodyMeasurements #bodyMassIndex,ボディマス指数 (BMI\))
* insert CodeDesignationRules(#BodyMeasurements #height,身長)
* insert CodeDesignationRules(#BodyMeasurements #hipCircumference, 臀囲)
* insert CodeDesignationRules(#BodyMeasurements #leanBodyMass,除脂肪体重 (LBM\))
* insert CodeDesignationRules(#BodyMeasurements #waistCircumference,胴囲)
* insert CodeDesignationRules(#BodyMeasurements #boneMass,骨量)
* insert CodeDesignationRules(#Diving,ダイビング)
* insert CodeDesignationRules(#Diving #underwaterDepth,水深)
* insert CodeDesignationRules(#Diving #waterTemperature,水温)
* insert CodeDesignationRules(#Hearing,聴覚)
* insert CodeDesignationRules(#Hearing #environmentalAudioExposure,環境音レベル)
* insert CodeDesignationRules(#Hearing #environmentalAudioExposureEvent,ノイズ通知)
* insert CodeDesignationRules(#Hearing #environmentalSoundReduction,環境音除去)
* insert CodeDesignationRules(#Hearing #headphoneAudioExposure,ヘッドフォン音量)
* insert CodeDesignationRules(#Hearing #headphoneAudioExposureEvent,ヘッドフォン通知)
* insert CodeDesignationRules(#Heart,心臓)
* insert CodeDesignationRules(#Heart #electrocardiogram,心電図 (ECG\))
* insert CodeDesignationRules(#Heart #heartBeatSeries,心拍)
* insert CodeDesignationRules(#LabAndTestResults,検査結果)
* insert CodeDesignationRules(#LabAndTestResults #bloodGlucose,血糖値)
* insert CodeDesignationRules(#LabAndTestResults #electrodermalActivity,皮膚電位)
* insert CodeDesignationRules(#LabAndTestResults #forcedExpiratoryVolume1,努力呼気肺活量(1秒\))
* insert CodeDesignationRules(#LabAndTestResults #forcedVitalCapacity,努力性肺活量)
* insert CodeDesignationRules(#LabAndTestResults #inhalerUsage,吸入器の使用状況)
* insert CodeDesignationRules(#LabAndTestResults #insulinDelivery,インスリン放出)
* insert CodeDesignationRules(#LabAndTestResults #numberOfTimesFallen,転倒回数)
* insert CodeDesignationRules(#LabAndTestResults #peakExpiratoryFlowRate,最大呼気流量)
* insert CodeDesignationRules(#LabAndTestResults #peripheralPerfusionIndex,灌流指標)
* insert CodeDesignationRules(#LabAndTestResults #timeInDaylight,日光の下で過ごした時間)
* insert CodeDesignationRules(#LabAndTestResults #inspiratoryTime,吸気時間)
* insert CodeDesignationRules(#LabAndTestResults #ventilationCycleTime,換気サイクルタイム)
* insert CodeDesignationRules(#LabAndTestResults #minuteVolume,分時換気量)
* insert CodeDesignationRules(#LabAndTestResults #breathCarbonMonoxide,呼気一酸化炭素濃度)
* insert CodeDesignationRules(#Mindfulness,マインドフルネス)
* insert CodeDesignationRules(#Mindfulness #mindfulSession,マインドフル時間)
* insert CodeDesignationRules(#Sleep,睡眠)
* insert CodeDesignationRules(#Sleep #sleepAnalysis,睡眠)
* insert CodeDesignationRules(#Sleep #sleepEpisode,睡眠エピソード)
* insert CodeDesignationRules(#Sleep #snoreIndex,いびき指数)
* insert CodeDesignationRules(#Sleep #snoreEvent,いびきイベント)
* insert CodeDesignationRules(#Sleep #sleepAHI,無呼吸低呼吸指数)
* insert CodeDesignationRules(#Sleep #sleepArousalIndex,覚醒反応指数)
* insert CodeDesignationRules(#Sleep #appleSleepingBreathingDisturbances,呼吸の乱れ)
* insert CodeDesignationRules(#Sleep #sleepApneaEvent,睡眠時無呼吸の通知)
* insert CodeDesignationRules(#Mobility,歩行)
* insert CodeDesignationRules(#Mobility #appleWalkingSteadiness,歩行安定性)
* insert CodeDesignationRules(#Mobility #appleWalkingSteadinessEvent,歩行安定性通知)
* insert CodeDesignationRules(#Mobility #sixMinuteWalkTestDistance,6分間歩行)
* insert CodeDesignationRules(#Mobility #walkingSpeed,歩行速度)
* insert CodeDesignationRules(#Mobility #walkingStepLength,ステップの長さ(歩幅\))
* insert CodeDesignationRules(#Mobility #walkingAsymmetryPercentage,歩行非対称性)
* insert CodeDesignationRules(#Mobility #walkingDoubleSupportPercentage,歩行両脚支持時間)
* insert CodeDesignationRules(#Mobility #stairAscentSpeed,階段速度: 上昇)
* insert CodeDesignationRules(#Mobility #stairDescentSpeed,階段速度: 下降)
* insert CodeDesignationRules(#Nutrition,栄養)
* insert CodeDesignationRules(#Nutrition #dietaryBiotin,ビオチン)
* insert CodeDesignationRules(#Nutrition #dietaryCaffeine,カフェイン)
* insert CodeDesignationRules(#Nutrition #dietaryCalcium,カルシウム)
* insert CodeDesignationRules(#Nutrition #dietaryCarbohydrates,炭水化物)
* insert CodeDesignationRules(#Nutrition #dietaryChloride,塩化物)
* insert CodeDesignationRules(#Nutrition #dietaryCholesterol,食物中のコレステロール)
* insert CodeDesignationRules(#Nutrition #dietaryChromium,クロム)
* insert CodeDesignationRules(#Nutrition #dietaryCopper,銅)
* insert CodeDesignationRules(#Nutrition #dietaryEnergyConsumed,摂取エネルギー)
* insert CodeDesignationRules(#Nutrition #dietaryEnergyFromFat,脂肪からのエネルギー)
* insert CodeDesignationRules(#Nutrition #dietaryFatMonounsaturated,一価不飽和脂肪酸)
* insert CodeDesignationRules(#Nutrition #dietaryFatPolyunsaturated,多価不飽和脂肪酸)
* insert CodeDesignationRules(#Nutrition #dietaryFatUnsaturated,不飽和脂肪酸)
* insert CodeDesignationRules(#Nutrition #dietaryTransFat,トランス脂肪酸)
* insert CodeDesignationRules(#Nutrition #dietaryFatSaturated,飽和脂肪酸)
* insert CodeDesignationRules(#Nutrition #dietaryFatTotal,総脂肪)
* insert CodeDesignationRules(#Nutrition #dietaryFiber,食物繊維)
* insert CodeDesignationRules(#Nutrition #dietaryFolateOrFolicAcid,葉酸塩・葉酸)
* insert CodeDesignationRules(#Nutrition #dietaryFolate,葉酸塩)
* insert CodeDesignationRules(#Nutrition #dietaryFolicAcid,葉酸)
* insert CodeDesignationRules(#Nutrition #dietaryIodine,ヨウ素)
* insert CodeDesignationRules(#Nutrition #dietaryIron,鉄分)
* insert CodeDesignationRules(#Nutrition #dietaryMagnesium,マグネシウム)
* insert CodeDesignationRules(#Nutrition #dietaryManganese,マンガン)
* insert CodeDesignationRules(#Nutrition #dietaryMolybdenum,モリブデン)
* insert CodeDesignationRules(#Nutrition #dietaryNiacin,ナイアシン)
* insert CodeDesignationRules(#Nutrition #dietaryPantothenicAcid,パントテン酸)
* insert CodeDesignationRules(#Nutrition #dietaryPhosphorus,リン)
* insert CodeDesignationRules(#Nutrition #dietaryPotassium,カリウム)
* insert CodeDesignationRules(#Nutrition #dietaryProtein,タンパク質)
* insert CodeDesignationRules(#Nutrition #dietaryRiboflavin,ビタミンB2)
* insert CodeDesignationRules(#Nutrition #dietarySelenium,セレン)
* insert CodeDesignationRules(#Nutrition #dietarySodium,ナトリウム)
* insert CodeDesignationRules(#Nutrition #dietarySugar,食物中の糖分)
* insert CodeDesignationRules(#Nutrition #dietaryThiamin,チアミン)
* insert CodeDesignationRules(#Nutrition #dietaryVitaminA,ビタミンA)
* insert CodeDesignationRules(#Nutrition #dietaryVitaminB12,ビタミンB12)
* insert CodeDesignationRules(#Nutrition #dietaryVitaminB6,ビタミンB6)
* insert CodeDesignationRules(#Nutrition #dietaryVitaminC,ビタミンC)
* insert CodeDesignationRules(#Nutrition #dietaryVitaminD,ビタミンD)
* insert CodeDesignationRules(#Nutrition #dietaryVitaminE,ビタミンE)
* insert CodeDesignationRules(#Nutrition #dietaryVitaminK,ビタミンK)
* insert CodeDesignationRules(#Nutrition #dietaryWater,水分)
* insert CodeDesignationRules(#Nutrition #dietaryZinc,亜鉛)
* insert CodeDesignationRules(#ReproductiveHealth,周期記録)
* insert CodeDesignationRules(#ReproductiveHealth #basalBodyTemperature,基礎体温)
* insert CodeDesignationRules(#ReproductiveHealth #cervicalMucusQuality,頸管粘液の質)
* insert CodeDesignationRules(#ReproductiveHealth #contraceptive,避妊方法)
* insert CodeDesignationRules(#ReproductiveHealth #intermenstrualBleeding,点状出血)
* insert CodeDesignationRules(#ReproductiveHealth #irregularMenstrualCycles,不調な周期)
* insert CodeDesignationRules(#ReproductiveHealth #infrequentMenstrualCycles,希発月経)
* insert CodeDesignationRules(#ReproductiveHealth #lactation,授乳)
* insert CodeDesignationRules(#ReproductiveHealth #menstrualFlow,月経)
* insert CodeDesignationRules(#ReproductiveHealth #menstrualPeriod,月経周期)
* insert CodeDesignationRules(#ReproductiveHealth #ovulationTestResult,排卵検査結果)
* insert CodeDesignationRules(#ReproductiveHealth #persistentIntermenstrualBleeding,持続性の点状出血)
* insert CodeDesignationRules(#ReproductiveHealth #pregnancy,妊娠)
* insert CodeDesignationRules(#ReproductiveHealth #pregnancyTestResult,妊娠検査結果)
* insert CodeDesignationRules(#ReproductiveHealth #progesteroneTestResult,プロゲステロン検査結果)
* insert CodeDesignationRules(#ReproductiveHealth #prolongedMenstrualPeriods,過長月経)
* insert CodeDesignationRules(#ReproductiveHealth #sexualActivity,性行為)
* insert CodeDesignationRules(#ReproductiveHealth #bleedingAfterPregnancy,妊娠後の出血)
* insert CodeDesignationRules(#ReproductiveHealth #bleedingDuringPregnancy,妊娠中の出血)
* insert CodeDesignationRules(#SelfCare,セルフケア)
* insert CodeDesignationRules(#SelfCare #handwashingEvent,手洗い)
* insert CodeDesignationRules(#SelfCare #toothbrushingEvent,歯磨き)
* insert CodeDesignationRules(#Symptom,症状)
* insert CodeDesignationRules(#Symptom #abdominalCramps,腹部疝痛)
* insert CodeDesignationRules(#Symptom #acne,痤瘡)
* insert CodeDesignationRules(#Symptom #appetiteChanges,食欲の変化)
* insert CodeDesignationRules(#Symptom #bladderIncontinence,尿失禁)
* insert CodeDesignationRules(#Symptom #bloating,腹部膨満感)
* insert CodeDesignationRules(#Symptom #breastPain,乳房痛)
* insert CodeDesignationRules(#Symptom #chestTightnessOrPain,胸の苦しさや痛み)
* insert CodeDesignationRules(#Symptom #chills,悪寒)
* insert CodeDesignationRules(#Symptom #constipation,便秘)
* insert CodeDesignationRules(#Symptom #coughing,せき)
* insert CodeDesignationRules(#Symptom #diarrhea,下痢)
* insert CodeDesignationRules(#Symptom #dizziness,めまい)
* insert CodeDesignationRules(#Symptom #drySkin,乾燥肌)
* insert CodeDesignationRules(#Symptom #fainting,失神)
* insert CodeDesignationRules(#Symptom #fatigue,疲労)
* insert CodeDesignationRules(#Symptom #fever,発熱)
* insert CodeDesignationRules(#Symptom #generalizedBodyAche,体および筋肉の痛み)
* insert CodeDesignationRules(#Symptom #hairLoss,脱毛)
* insert CodeDesignationRules(#Symptom #headache,頭痛)
* insert CodeDesignationRules(#Symptom #heartburn,胸やけ)
* insert CodeDesignationRules(#Symptom #hotFlashes,ほてり)
* insert CodeDesignationRules(#Symptom #lossOfSmell,嗅覚喪失)
* insert CodeDesignationRules(#Symptom #lossOfTaste,味覚喪失)
* insert CodeDesignationRules(#Symptom #lowerBackPain,腰痛)
* insert CodeDesignationRules(#Symptom #memoryLapse,記憶力の衰え)
* insert CodeDesignationRules(#Symptom #moodChanges,気分の変化)
* insert CodeDesignationRules(#Symptom #nausea,吐き気)
* insert CodeDesignationRules(#Symptom #nightSweats,寝汗)
* insert CodeDesignationRules(#Symptom #pelvicPain,骨盤痛)
* insert CodeDesignationRules(#Symptom #rapidPoundingOrFlutteringHeartbeat,頻脈(頻拍\)、激しい鼓動、または不安定な鼓動)
* insert CodeDesignationRules(#Symptom #runnyNose,鼻水)
* insert CodeDesignationRules(#Symptom #shortnessOfBreath,息切れ)
* insert CodeDesignationRules(#Symptom #sinusCongestion,うっ血)
* insert CodeDesignationRules(#Symptom #skippedHeartbeat,結滞(欠損\))
* insert CodeDesignationRules(#Symptom #sleepChanges,睡眠の変化)
* insert CodeDesignationRules(#Symptom #soreThroat,喉の痛み)
* insert CodeDesignationRules(#Symptom #vaginalDryness,膣の乾燥)
* insert CodeDesignationRules(#Symptom #vomiting,嘔吐)
* insert CodeDesignationRules(#Symptom #wheezing,喘鳴)
* insert CodeDesignationRules(#UVExposure,UV指数)
* insert CodeDesignationRules(#UVExposure #uvExposure,UV指数)
* insert CodeDesignationRules(#VitalSigns,バイタル)
* insert CodeDesignationRules(#VitalSigns #atrialFibrillationBurden,心房細動履歴)
* insert CodeDesignationRules(#VitalSigns #bloodPressure,血圧)
* insert CodeDesignationRules(#VitalSigns #bloodPressureDiastolic,拡張期血圧)
* insert CodeDesignationRules(#VitalSigns #bloodPressureSystolic,収縮期血圧)
* insert CodeDesignationRules(#VitalSigns #bodyTemperature,体温)
* insert CodeDesignationRules(#VitalSigns #heartRate,心拍数)
* insert CodeDesignationRules(#VitalSigns #heartRateVariabilitySDNN,心拍変動)
* insert CodeDesignationRules(#VitalSigns #heartRateRecoveryOneMinute,心拍数回復)
* insert CodeDesignationRules(#VitalSigns #highHeartRateEvent,高心拍の通知)
* insert CodeDesignationRules(#VitalSigns #irregularHeartRhythmEvent,不規則な心拍の通知)
* insert CodeDesignationRules(#VitalSigns #lowHeartRateEvent,低心拍の通知)
* insert CodeDesignationRules(#VitalSigns #oxygenSaturation,取り込まれた酸素のレベル (血中酸素濃度\))
* insert CodeDesignationRules(#VitalSigns #respiratoryRate,呼吸数)
* insert CodeDesignationRules(#VitalSigns #restingHeartRate,安静時心拍数)
* insert CodeDesignationRules(#VitalSigns #walkingHeartRateAverage,歩行時平均心拍数)
* insert CodeDesignationRules(#VitalSigns #rrInterval,RR間隔)
* insert CodeDesignationRules(#WorkoutActivity,ワークアウト アクティビティ)
* insert CodeDesignationRules(#WorkoutActivity #americanFootball,アメリカンフットボール)
* insert CodeDesignationRules(#WorkoutActivity #archery,アーチェリー)
* insert CodeDesignationRules(#WorkoutActivity #australianFootball,オーストラリアンフットボール)
* insert CodeDesignationRules(#WorkoutActivity #badminton,バドミントン)
* insert CodeDesignationRules(#WorkoutActivity #barre,バレエ)
* insert CodeDesignationRules(#WorkoutActivity #baseball,野球)
* insert CodeDesignationRules(#WorkoutActivity #basketball,バスケットボール)
* insert CodeDesignationRules(#WorkoutActivity #bowling,ボウリング)
* insert CodeDesignationRules(#WorkoutActivity #boxing,ボクシング)
* insert CodeDesignationRules(#WorkoutActivity #cardioDance,カーディオダンス)
* insert CodeDesignationRules(#WorkoutActivity #climbing,クライミング)
* insert CodeDesignationRules(#WorkoutActivity #cooldown,クールダウン)
* insert CodeDesignationRules(#WorkoutActivity #coreTraining,コアトレーニング)
* insert CodeDesignationRules(#WorkoutActivity #cricket,クリケット)
* insert CodeDesignationRules(#WorkoutActivity #crossCountrySkiing,クロスカントリースキー)
* insert CodeDesignationRules(#WorkoutActivity #crossTraining,クロストレーニング)
* insert CodeDesignationRules(#WorkoutActivity #curling,カーリング)
* insert CodeDesignationRules(#WorkoutActivity #cycling,サイクリング)
* insert CodeDesignationRules(#WorkoutActivity #dance,ダンス)
* insert CodeDesignationRules(#WorkoutActivity #danceInspiredTraining,ダンスインスパイアード トレーニング)
* insert CodeDesignationRules(#WorkoutActivity #discSports,フライングディスクスポーツ)
* insert CodeDesignationRules(#WorkoutActivity #downhillSkiing,ダウンヒルスキー)
* insert CodeDesignationRules(#WorkoutActivity #elliptical,エリプティカル)
* insert CodeDesignationRules(#WorkoutActivity #equestrianSports,乗馬関連スポーツ)
* insert CodeDesignationRules(#WorkoutActivity #fencing,フェンシング)
* insert CodeDesignationRules(#WorkoutActivity #fishing,釣り)
* insert CodeDesignationRules(#WorkoutActivity #fitnessGaming,フィットネスゲーム)
* insert CodeDesignationRules(#WorkoutActivity #flexibility,柔軟体操)
* insert CodeDesignationRules(#WorkoutActivity #functionalStrengthTraining,機能的筋力トレーニング)
* insert CodeDesignationRules(#WorkoutActivity #golf,ゴルフ)
* insert CodeDesignationRules(#WorkoutActivity #gymnastics,体操競技)
* insert CodeDesignationRules(#WorkoutActivity #handball,ハンドボール)
* insert CodeDesignationRules(#WorkoutActivity #handCycling,ハンドサイクリング)
* insert CodeDesignationRules(#WorkoutActivity #highIntensityIntervalTraining,高強度インターバルトレーニング)
* insert CodeDesignationRules(#WorkoutActivity #hiking,ハイキング)
* insert CodeDesignationRules(#WorkoutActivity #hockey,ホッケー)
* insert CodeDesignationRules(#WorkoutActivity #hunting,ハンティング)
* insert CodeDesignationRules(#WorkoutActivity #jumpRope,縄跳び)
* insert CodeDesignationRules(#WorkoutActivity #kickboxing,キックボクシング)
* insert CodeDesignationRules(#WorkoutActivity #lacrosse,ラクロス)
* insert CodeDesignationRules(#WorkoutActivity #martialArts,マーシャルアーツ)
* insert CodeDesignationRules(#WorkoutActivity #mindAndBody,マインドアンドボディ)
* insert CodeDesignationRules(#WorkoutActivity #mixedCardio,複合カーディオトレーニング)
* insert CodeDesignationRules(#WorkoutActivity #mixedMetabolicCardioTraining,(Deprecated\) 複合カーディオトレーニング)
* insert CodeDesignationRules(#WorkoutActivity #other,その他)
* insert CodeDesignationRules(#WorkoutActivity #paddleSports,パドリング)
* insert CodeDesignationRules(#WorkoutActivity #pickleball,ピックルボール)
* insert CodeDesignationRules(#WorkoutActivity #pilates,ピラティス)
* insert CodeDesignationRules(#WorkoutActivity #play,遊び)
* insert CodeDesignationRules(#WorkoutActivity #preparationAndRecovery,ローリング)
* insert CodeDesignationRules(#WorkoutActivity #racquetball,ラケットボール)
* insert CodeDesignationRules(#WorkoutActivity #rowing,ローイング)
* insert CodeDesignationRules(#WorkoutActivity #rugby,ラグビー)
* insert CodeDesignationRules(#WorkoutActivity #running,ランニング)
* insert CodeDesignationRules(#WorkoutActivity #sailing,セーリング)
* insert CodeDesignationRules(#WorkoutActivity #skatingSports,スケート)
* insert CodeDesignationRules(#WorkoutActivity #snowboarding,スノーボード)
* insert CodeDesignationRules(#WorkoutActivity #snowSports,ウインタースポーツ)
* insert CodeDesignationRules(#WorkoutActivity #soccer,サッカー)
* insert CodeDesignationRules(#WorkoutActivity #socialDance,社交ダンス)
* insert CodeDesignationRules(#WorkoutActivity #softball,ソフトボール)
* insert CodeDesignationRules(#WorkoutActivity #squash,スカッシュ)
* insert CodeDesignationRules(#WorkoutActivity #stairClimbing,ステアステッパー)
* insert CodeDesignationRules(#WorkoutActivity #stairs,階段昇降)
* insert CodeDesignationRules(#WorkoutActivity #stepTraining,ステップトレーニング)
* insert CodeDesignationRules(#WorkoutActivity #surfingSports,サーフィン)
* insert CodeDesignationRules(#WorkoutActivity #swimBikeRun,マルチスポーツ)
* insert CodeDesignationRules(#WorkoutActivity #swimming,スイミング)
* insert CodeDesignationRules(#WorkoutActivity #tableTennis,卓球)
* insert CodeDesignationRules(#WorkoutActivity #taiChi,太極拳)
* insert CodeDesignationRules(#WorkoutActivity #tennis,テニス)
* insert CodeDesignationRules(#WorkoutActivity #trackAndField,陸上競技)
* insert CodeDesignationRules(#WorkoutActivity #traditionalStrengthTraining,伝統的筋力トレーニング)
* insert CodeDesignationRules(#WorkoutActivity #transition,移行時間)
* insert CodeDesignationRules(#WorkoutActivity #underwaterDiving,ダイビング)
* insert CodeDesignationRules(#WorkoutActivity #volleyball,バレーボール)
* insert CodeDesignationRules(#WorkoutActivity #walking,ウォーキング)
* insert CodeDesignationRules(#WorkoutActivity #waterFitness,ウォーターフィットネス)
* insert CodeDesignationRules(#WorkoutActivity #waterPolo,水球)
* insert CodeDesignationRules(#WorkoutActivity #waterSports,ウォータースポーツ)
* insert CodeDesignationRules(#WorkoutActivity #wheelchairRunPace,車椅子ペースランニング)
* insert CodeDesignationRules(#WorkoutActivity #wheelchairWalkPace,車椅子ペースウォーキング)
* insert CodeDesignationRules(#WorkoutActivity #wrestling,レスリング)
* insert CodeDesignationRules(#WorkoutActivity #yoga,ヨガ)
* insert CodeDesignationRules(#WorkoutActivity #backExtension,バックエクステンション)
* insert CodeDesignationRules(#WorkoutActivity #barbellShoulderPress,バーベルショルダープレス)
* insert CodeDesignationRules(#WorkoutActivity #benchPress,ベンチプレス)
* insert CodeDesignationRules(#WorkoutActivity #benchSitUp,シットアップベンチ)
* insert CodeDesignationRules(#WorkoutActivity #biking,自転車)
* insert CodeDesignationRules(#WorkoutActivity #bikingStationary,エアロバイク)
* insert CodeDesignationRules(#WorkoutActivity #bootCamp,ブートキャンプ)
* insert CodeDesignationRules(#WorkoutActivity #burpee,バーピー)
* insert CodeDesignationRules(#WorkoutActivity #calisthenics,キャリステニクス)
* insert CodeDesignationRules(#WorkoutActivity #crunch,クランチ)
* insert CodeDesignationRules(#WorkoutActivity #deadlift,デッドリフト)
* insert CodeDesignationRules(#WorkoutActivity #dumbbellCurlLeftArm,ダンベル カール 左腕)
* insert CodeDesignationRules(#WorkoutActivity #dumbbellCurlRightArm,ダンベル カール 右腕)
* insert CodeDesignationRules(#WorkoutActivity #dumbbellFrontRaise,ダンベル ラテラル レイズ)
* insert CodeDesignationRules(#WorkoutActivity #dumbbellLateralRaise,ダンベル ラテラル レイズ)
* insert CodeDesignationRules(#WorkoutActivity #dumbbellTricepsExtensionLeftArm,ダンベル トライセップス エクステンション 左腕)
* insert CodeDesignationRules(#WorkoutActivity #dumbbellTricepsExtensionRightArm,ダンベル トライセップス エクステンション 右腕)
* insert CodeDesignationRules(#WorkoutActivity #dumbbellTricepsExtensionTwoArm,ダンベル トライセップス エクステンション 両腕)
* insert CodeDesignationRules(#WorkoutActivity #exerciseClass,体操教室)
* insert CodeDesignationRules(#WorkoutActivity #forwardTwist,前ひねり)
* insert CodeDesignationRules(#WorkoutActivity #frisbeeDisc,フリスビーディスク)
* insert CodeDesignationRules(#WorkoutActivity #guidedBreathing,ガイド付き呼吸法)
* insert CodeDesignationRules(#WorkoutActivity #iceHockey,アイスホッケー)
* insert CodeDesignationRules(#WorkoutActivity #iceSkating,アイススケート)
* insert CodeDesignationRules(#WorkoutActivity #jumpingJack,ジャンピングジャック)
* insert CodeDesignationRules(#WorkoutActivity #latPullDown,ラットプルダウン)
* insert CodeDesignationRules(#WorkoutActivity #lunge,ランジ)
* insert CodeDesignationRules(#WorkoutActivity #meditation,瞑想)
* insert CodeDesignationRules(#WorkoutActivity #paraGliding,パラグライダー)
* insert CodeDesignationRules(#WorkoutActivity #plank,プランク)
* insert CodeDesignationRules(#WorkoutActivity #rockClimbing,ロッククライミング)
* insert CodeDesignationRules(#WorkoutActivity #rollerHockey,ローラーホッケー)
* insert CodeDesignationRules(#WorkoutActivity #rowingMachine,ローイングマシン)
* insert CodeDesignationRules(#WorkoutActivity #runningTreadmill,ランニング トレッドミル)
* insert CodeDesignationRules(#WorkoutActivity #scubaDiving,スキューバダイビング)
* insert CodeDesignationRules(#WorkoutActivity #skiing,スキー)
* insert CodeDesignationRules(#WorkoutActivity #snowshoeing,雪上歩行)
* insert CodeDesignationRules(#WorkoutActivity #squat,スクワット)
* insert CodeDesignationRules(#WorkoutActivity #strengthTraining,筋力トレーニング)
* insert CodeDesignationRules(#WorkoutActivity #stretching,ストレッチ)
* insert CodeDesignationRules(#WorkoutActivity #swimmingOpenWater,オープンウォータースイミング)
* insert CodeDesignationRules(#WorkoutActivity #swimmingPool,プールスイミング)
* insert CodeDesignationRules(#WorkoutActivity #upperTwist,アッパーツイスト)
* insert CodeDesignationRules(#WorkoutActivity #weightlifting,ウェイトリフティング)
* insert CodeDesignationRules(#WorkoutActivity #wheelchair,車椅子)
* insert CodeDesignationRules(#WorkoutActivity #workout,ワークアウト)
* insert CodeDesignationRules(#Audiogram,オージオグラム)
* insert CodeDesignationRules(#Audiogram #hearingSensitivity,聴力)
* insert CodeDesignationRules(#food,食事)
* insert CodeDesignationRules(#medicationAdherence,服薬アドヒアランス率)
* insert CodeDesignationRules(#Mind,心の状態)
* insert CodeDesignationRules(#Mind #stateOfMind,心の状態)
* insert CodeDesignationRules(#Mind #gad7,不安障害リスク)
* insert CodeDesignationRules(#Mind #phq9,うつ病リスク)

//Unit
* insert UnitRules(#Activity #distanceWalkingRunning, #km)
* insert UnitRules(#Activity #runningGroundContactTime, #s)
* insert UnitRules(#Activity #runningPower, #W)
* insert UnitRules(#Activity #runningSpeed, #m/s)
* insert UnitRules(#Activity #runningStrideLength, #m)
* insert UnitRules(#Activity #runningVerticalOscillation, #m)
* insert UnitRules(#Activity #distanceCycling, #m)
* insert UnitRules(#Activity #distanceWheelchair, #m)
* insert UnitRules(#Activity #distanceSwimming, #m)
* insert UnitRules(#Activity #distanceDownhillSnowSports, #m)
* insert UnitRules(#Activity #basalEnergyBurned, #kcal)
* insert UnitRules(#Activity #activeEnergyBurned, #kcal)
* insert UnitRules(#Activity #totalEnergyBurned, #kcal)
* insert UnitRules(#Activity #elevationGained, #m)
* insert UnitRules(#Activity #appleExerciseTime, #min)
* insert UnitRules(#Activity #appleMoveTime, #min)
* insert UnitRules(#Activity #appleStandTime, #min)
* insert UnitRules(#Activity #vo2Max, #ml/kg/min)
* insert UnitRules(#Activity #cyclingFunctionalThresholdPower, #W)
* insert UnitRules(#Activity #cyclingPower, #W)
* insert UnitRules(#Activity #cyclingSpeed, #km/h)
* insert UnitRules(#Activity #distance, #m)
* insert UnitRules(#Activity #power, #W)
* insert UnitRules(#Activity #physicalEffort, #kcal/(kg.h\))
* insert UnitRules(#Activity #speed, #m/s)
* insert UnitRules(#Activity #pace, #min/km)

* insert UnitRules(#Activity #crossCountrySkiingSpeed, #km/h)
* insert UnitRules(#Activity #distanceCrossCountrySkiing, #km)
* insert UnitRules(#Activity #paddleSportsSpeed, #km/h)
* insert UnitRules(#Activity #distancePaddleSports, #km)
* insert UnitRules(#Activity #rowingSpeed, #km/h)
* insert UnitRules(#Activity #distanceRowing, #km)
* insert UnitRules(#Activity #distanceSkatingSports, #km)

* insert UnitRules(#Diving #underwaterDepth, #m)
* insert UnitRules(#Diving #waterTemperature, #Cel)
* insert UnitRules(#AlcoholConsumption #bloodAlcoholContent, #%)

* insert UnitRules(#BodyMeasurements #appleSleepingWristTemperature, #Cel)
* insert UnitRules(#BodyMeasurements #height, #cm)
* insert UnitRules(#BodyMeasurements #bodyMass, #kg)
* insert UnitRules(#BodyMeasurements #leanBodyMass, #kg)
* insert UnitRules(#BodyMeasurements #bodyFatPercentage, #%)
* insert UnitRules(#BodyMeasurements #waistCircumference, #cm)
* insert UnitRules(#BodyMeasurements #hipCircumference, #cm)
* insert UnitRules(#BodyMeasurements #boneMass, #kg)
* insert UnitRules(#Hearing #environmentalAudioExposure, #dB)
* insert UnitRules(#Hearing #environmentalSoundReduction, #dB)
* insert UnitRules(#Hearing #headphoneAudioExposure, #dB)
* insert UnitRules(#VitalSigns #atrialFibrillationBurden, #%)
* insert UnitRules(#VitalSigns #heartRate, #/min)
* insert UnitRules(#VitalSigns #restingHeartRate, #/min)
* insert UnitRules(#VitalSigns #walkingHeartRateAverage, #/min)
* insert UnitRules(#VitalSigns #heartRateVariabilitySDNN, #ms)
* insert UnitRules(#VitalSigns #heartRateRecoveryOneMinute, #/min)
* insert UnitRules(#VitalSigns #oxygenSaturation, #%)
* insert UnitRules(#VitalSigns #bodyTemperature, #Cel)
* insert UnitRules(#VitalSigns #bloodPressureDiastolic, #mm[Hg])
* insert UnitRules(#VitalSigns #bloodPressureSystolic, #mm[Hg])
* insert UnitRules(#VitalSigns #respiratoryRate, #/min)
* insert UnitRules(#VitalSigns #rrInterval, #ms)
* insert UnitRules(#LabAndTestResults #bloodGlucose, #mmol/L)
* insert UnitRules(#LabAndTestResults #electrodermalActivity, #S)
* insert UnitRules(#LabAndTestResults #forcedExpiratoryVolume1, #L)
* insert UnitRules(#LabAndTestResults #forcedVitalCapacity, #L)
* insert UnitRules(#LabAndTestResults #insulinDelivery, #[IU])
* insert UnitRules(#LabAndTestResults #peakExpiratoryFlowRate, #L/min)
* insert UnitRules(#LabAndTestResults #peripheralPerfusionIndex, #%)
* insert UnitRules(#LabAndTestResults #timeInDaylight, #min)
* insert UnitRules(#LabAndTestResults #inspiratoryTime, #s)
* insert UnitRules(#LabAndTestResults #ventilationCycleTime, #s)
* insert UnitRules(#LabAndTestResults #minuteVolume, #mL/min)
* insert UnitRules(#LabAndTestResults #breathCarbonMonoxide, #[ppm])
* insert UnitRules(#Sleep #sleepAHI, #/h)
* insert UnitRules(#Sleep #sleepArousalIndex, #/h)
* insert UnitRules(#Mobility #appleWalkingSteadiness, #%)
* insert UnitRules(#Mobility #sixMinuteWalkTestDistance, #m/(6.min\))
* insert UnitRules(#Mobility #walkingSpeed, #m/s)
* insert UnitRules(#Mobility #walkingStepLength, #m)
* insert UnitRules(#Mobility #walkingAsymmetryPercentage, #%)
* insert UnitRules(#Mobility #walkingDoubleSupportPercentage, #%)
* insert UnitRules(#Mobility #stairAscentSpeed, #m/s)
* insert UnitRules(#Mobility #stairDescentSpeed, #m/s)
* insert UnitRules(#Nutrition #dietaryBiotin, #ug)
* insert UnitRules(#Nutrition #dietaryCaffeine, #mg)
* insert UnitRules(#Nutrition #dietaryCalcium, #mg)
* insert UnitRules(#Nutrition #dietaryCarbohydrates, #g)
* insert UnitRules(#Nutrition #dietaryChloride, #g)
* insert UnitRules(#Nutrition #dietaryCholesterol, #mg)
* insert UnitRules(#Nutrition #dietaryChromium, #ug)
* insert UnitRules(#Nutrition #dietaryCopper, #mg)
* insert UnitRules(#Nutrition #dietaryEnergyConsumed, #kcal)
* insert UnitRules(#Nutrition #dietaryEnergyFromFat, #kcal)
* insert UnitRules(#Nutrition #dietaryFatMonounsaturated, #g)
* insert UnitRules(#Nutrition #dietaryFatPolyunsaturated, #g)
* insert UnitRules(#Nutrition #dietaryFatUnsaturated, #g)
* insert UnitRules(#Nutrition #dietaryTransFat, #g)
* insert UnitRules(#Nutrition #dietaryFatSaturated, #g)
* insert UnitRules(#Nutrition #dietaryFatTotal, #g)
* insert UnitRules(#Nutrition #dietaryFiber, #g)
* insert UnitRules(#Nutrition #dietaryFolateOrFolicAcid, #ug)
* insert UnitRules(#Nutrition #dietaryFolate, #ug)
* insert UnitRules(#Nutrition #dietaryFolicAcid, #ug)
* insert UnitRules(#Nutrition #dietaryIodine, #ug)
* insert UnitRules(#Nutrition #dietaryIron, #mg)
* insert UnitRules(#Nutrition #dietaryMagnesium, #mg)
* insert UnitRules(#Nutrition #dietaryManganese, #mg)
* insert UnitRules(#Nutrition #dietaryMolybdenum, #ug)
* insert UnitRules(#Nutrition #dietaryNiacin, #mg)
* insert UnitRules(#Nutrition #dietaryPantothenicAcid, #mg)
* insert UnitRules(#Nutrition #dietaryPhosphorus, #mg)
* insert UnitRules(#Nutrition #dietaryPotassium, #mg)
* insert UnitRules(#Nutrition #dietaryProtein, #g)
* insert UnitRules(#Nutrition #dietaryRiboflavin, #mg)
* insert UnitRules(#Nutrition #dietarySelenium, #ug)
* insert UnitRules(#Nutrition #dietarySodium, #mg)
* insert UnitRules(#Nutrition #dietarySugar, #g)
* insert UnitRules(#Nutrition #dietaryThiamin, #mg)
* insert UnitRules(#Nutrition #dietaryVitaminA, #ug)
* insert UnitRules(#Nutrition #dietaryVitaminB12, #ug)
* insert UnitRules(#Nutrition #dietaryVitaminB6, #mg)
* insert UnitRules(#Nutrition #dietaryVitaminC, #mg)
* insert UnitRules(#Nutrition #dietaryVitaminD, #ug)
* insert UnitRules(#Nutrition #dietaryVitaminE, #mg)
* insert UnitRules(#Nutrition #dietaryVitaminK, #ug)
* insert UnitRules(#Nutrition #dietaryWater, #L)
* insert UnitRules(#Nutrition #dietaryZinc, #mg)
* insert UnitRules(#ReproductiveHealth #basalBodyTemperature, #Cel)
