CodeSystem: ObservationPGHD
Id: observation-pghd-codes
Title: "Observation PGHD Codes"
Description: """
Code defining the type of PGHD data
"""
* insert CodeSystemRules
* ^hierarchyMeaning = #grouped-by

* #Activity "Activity" ""
* #Activity #activeEnergyBurned "Active energy burned" "A quantity sample type that measures the amount of active energy the user has burned."
* #Activity #appleExerciseTime "Apple exercise time" "A quantity sample type that measures the amount of time the user spent exercising."
* #Activity #appleMoveTime "Apple move time" "A quantity sample type that measures the amount of time the user has spent performing activities that involve full-body movements during the specified day."
* #Activity #appleStandHour "Apple stand hour" "A category sample type that counts the number of hours in the day during which the user has stood and moved for at least one minute per hour."
* #Activity #appleStandTime "Apple stand time" "A quantity sample type that measures the amount of time the user has spent standing."
* #Activity #basalEnergyBurned "Basal energyBurned" "A quantity sample type that measures the resting energy burned by the user."
* #Activity #cyclingCadence "Cycling cadence" "Captures the user's cycling pedaling cadence. Each record represents a series of measurements."
* #Activity #cyclingFunctionalThresholdPower "Cycling functional threshold power" "A quantity sample type that measures the highest average power output the user can maintain for an hour."
* #Activity #cyclingPower "Cycling power" "A quantity sample type that measures power output by the user while cycling."
* #Activity #cyclingSpeed "Cycling speed" "A quantity sample type measuring the user's speed while cycling."
* #Activity #distance "Distance" "Captures distance travelled by the user since the last reading."
* #Activity #elevationGained "Elevation gained" "Captures the elevation gained by the user since the last reading."
* #Activity #totalEnergyBurned "Total energy burned" "Captures the user's steps cadence. Each record represents a series of measurements."
* #Activity #distanceCycling "Distance cycling" "A quantity sample type that measures the distance the user has moved by cycling."
* #Activity #distanceDownhillSnowSports "Distance downhill snow sports" "A quantity sample type that measures the distance the user has traveled while skiing or snowboarding."
* #Activity #distanceSwimming "Distance swimming" "A quantity sample type that measures the distance the user has moved while swimming."
* #Activity #distanceWalkingRunning "Distance walking running" "A quantity sample type that measures the distance the user has moved by walking or running."
* #Activity #distanceWheelchair "Distance wheelchair" "A quantity sample type that measures the distance the user has moved using a wheelchair."
* #Activity #flightsClimbed "Flights climbed" "A quantity sample type that measures the number flights of stairs that the user has climbed."
* #Activity #lowCardioFitnessEvent "Low cardio fitness event" "An event that indicates the user's VO2 max values consistently fall below a particular aerobic fitness threshold."
* #Activity #nikeFuel "NikeFuel" "A quantity sample type that measures the number of NikeFuel points the user has earned."
* #Activity #physicalEffort "Physical effort" "A quantity sample type that records an estimate of the energy the user using."
* #Activity #power "Power" "Captures the power generated by the user, e.g. during rowing with a power meter. Each record represents a series of measurements."
* #Activity #pushCount "Push count" "A quantity sample type that measures the number of pushes that the user has performed while using a wheelchair."
* #Activity #runningGroundContactTime "Running ground contact time" "A quantity sample type that measures the amount of time the runner's foot is in contact with the ground while running."
* #Activity #runningPower "Running power" "A quantity sample type that measures the rate of work required for the runner to maintain their speed."
* #Activity #runningSpeed "Running speed" "A quantity sample type that measures the runner's speed."
* #Activity #runningStrideLength "Running stride length" "A quantity sample type that measures the distance covered by a single step while running."
* #Activity #runningVerticalOscillation "Running vertical oscillation" "A quantity sample type measuring pelvis vertical range of motion during a single running stride."
* #Activity #stepsCadence "Steps cadence" "Captures the user's steps cadence. Each record represents a series of measurements."
* #Activity #stepCount "Step count" "A quantity sample type that measures the number of steps the user has taken."
* #Activity #speed "Speed" "Captures the user's speed, e.g. during running. Each record represents a series of measurements."
* #Activity #swimmingStrokeCount "Swimming stroke count" "A quantity sample type that measures the number of strokes performed while swimming."
* #Activity #vo2Max "VO2 max" "A quantity sample that measures the maximal oxygen consumption during exercise."
* #Activity #pace "Pace" "Pace at a specific point in time. Will be 0 if the user stops moving, otherwise the value will be in milliseconds/kilometer."
* #Activity #moderateActivity "Moderate activity" "Represents moderate (3.0-5.9 MET) activity."
* #Activity #vigorousActivity "Vigorous activity" "Represents vigorous (6.0- MET) activity."
* #Activity #moderateToVigorousActivity "Moderate to vigorous activity" "Weekly moderate to vigorous physical activity in minutes."
* #Activity #met "Met" ""
* #Activity #metByStandardRmr "Met by standard RMR" "Metabolic equivalent of task (MET) calculated based on either measured, estimated or reported exercise metabolic rate and the standard resting metabolic rate (RMR)."
* #Activity #crossCountrySkiingSpeed "Cross country skiing speed" "A quantity sample type measuring the user's speed while cross country skiing."
* #Activity #distanceCrossCountrySkiing "Distance cross country skiing" "A quantity sample type that measures the distance the user has moved while cross country skiing."
* #Activity #paddleSportsSpeed "Paddle sports speed" "A quantity sample type measuring the user's speed during paddle sports."
* #Activity #distancePaddleSports "Distance paddle sports" "A quantity sample type that measures the distance the user has moved during paddle sports."
* #Activity #rowingSpeed "Rowing speed" "A quantity sample type measuring the user's rowing speed."
* #Activity #distanceRowing "Distance rowing" "A quantity sample type measuring the distance the user has rowed."
* #Activity #distanceSkatingSports "Distance skating sports" "A quantity sample type that measures the distance the user has skated."
* #Activity #estimatedWorkoutEffortScore "Estimated workout effort score" "A quantity sample type that represents estimate of exertion score."
* #Activity #workoutEffortScore "Workout effort score" "A quantity sample type that represents exertion score."
* #AlcoholConsumption "Alcohol consumption" ""
* #AlcoholConsumption #bloodAlcoholContent "Blood alcohol content" "quantity sample type that measures the user's blood alcohol content."
* #AlcoholConsumption #numberOfAlcoholicBeverages "Number of alcoholic beverages" "A quantity sample type that measures the number of standard alcoholic drinks that the user has consumed."
* #BodyMeasurements "Body measurements" ""
* #BodyMeasurements #appleSleepingWristTemperature "Apple sleeping wrist temperature" "A quantity sample type that records the wrist temperature during sleep."
* #BodyMeasurements #bodyFatPercentage "Body fat percentage" "A quantity sample type that measures the user's body fat percentage."
* #BodyMeasurements #bodyMass "Body mass" "A quantity sample type that measures the user's weight."
* #BodyMeasurements #bodyMassIndex "Body mass index" "A quantity sample type that measures the user's body mass index."
* #BodyMeasurements #height "Height" "A quantity sample type that measures the user's height."
* #BodyMeasurements #hipCircumference "Hip circumference" "A quantity sample type that measures the user's hip circumference."
* #BodyMeasurements #leanBodyMass "Lean body mass" "A quantity sample type that measures the user's lean body mass."
* #BodyMeasurements #waistCircumference "Waist circumference" "A quantity sample type that measures the user's waist circumference."
* #BodyMeasurements #boneMass "Bone mass" "A quantity sample type that measures the user's bone mass"
* #Diving "Diving" ""
* #Diving #underwaterDepth "Underwater depth" "A quantity sample that records a person's depth underwater."
* #Diving #waterTemperature "Water temperature" "A quantity sample that records the water temperature."
* #Hearing "Hearing" ""
* #Hearing #environmentalAudioExposure "Environmental audio exposure" "A quantity sample type that measures audio exposure to sounds in the environment."
* #Hearing #environmentalAudioExposureEvent "Environmental audio exposure event" "A category sample type that records exposure to potentially damaging sounds from the environment."
* #Hearing #environmentalSoundReduction "Environmental sound reduction" "The environmental sound level reduced while user wearing AirPods Pro and using Active Noise Cancellation or Adaptive Transparency mode."
* #Hearing #headphoneAudioExposure "Headphone audio exposure" "A quantity sample type that measures audio exposure from headphones."
* #Hearing #headphoneAudioExposureEvent "Headphone audio exposure event" "A category sample type that records exposure to potentially damaging sounds from headphones."
* #Heart "Heart" ""
* #Heart #electrocardiogram "Electrocardiogram" "A type that identifies samples containing electrocardiogram data."
* #Heart #heartBeatSeries "Heart beat series" "A series sample containing heartbeat data."
* #LabAndTestResults "Lab and test results" ""
* #LabAndTestResults #bloodGlucose "Blood glucose" "A quantity sample type that measures the user's blood glucose level."
* #LabAndTestResults #electrodermalActivity "Electrodermal activity" "A quantity sample type that measures electrodermal activity."
* #LabAndTestResults #forcedExpiratoryVolume1 "Forced expiratory volume1" "A quantity sample type that measures the amount of air that can be forcibly exhaled from the lungs during the first second of a forced exhalation."
* #LabAndTestResults #forcedVitalCapacity "Forced vital capacity" "A quantity sample type that measures the amount of air that can be forcibly exhaled from the lungs after taking the deepest breath possible."
* #LabAndTestResults #inhalerUsage "Inhaler usage" "A quantity sample type that measures the number of puffs the user takes from their inhaler."
* #LabAndTestResults #insulinDelivery "Insulin delivery" "A quantity sample that measures the amount of insulin delivered."
* #LabAndTestResults #numberOfTimesFallen "Number of times fallen" "A quantity sample type that measures the number of times the user fell."
* #LabAndTestResults #peakExpiratoryFlowRate "Peak expiratory flow rate" "A quantity sample type that measures the user's maximum flow rate generated during a forceful exhalation."
* #LabAndTestResults #peripheralPerfusionIndex "Peripheral perfusion index" "A quantity sample type that measures the user's peripheral perfusion index."
* #LabAndTestResults #timeInDaylight "Time in daylight" "A quantity sample type that captures the amount of time the user spent in daylight."
* #LabAndTestResults #inspiratoryTime "Inspiratory time" "The duration of a person's inspiration, either a single measurement, or the result of aggregating several measurements made over time."
* #LabAndTestResults #ventilationCycleTime "Ventilation cycle time" "Represents the duration of a person's complete respiration."
* #LabAndTestResults #minuteVolume "Minute volume" "The volume of gas inhaled or exhaled from a person's lungs per minute."
* #LabAndTestResults #breathCarbonMonoxide "Breath carbon monoxide" "The amount of carbon monoxide gas present in a person's exhaled breath."
* #Mindfulness "Mindfulness" ""
* #Mindfulness #mindfulSession "Mindful session" "A category sample type for recording a mindful session."
* #Sleep "Sleep" ""
* #Sleep #sleepAnalysis "Sleep analysis" "A category sample type for sleep analysis information."
* #Sleep #sleepEpisode "Sleep episode" "Represents one sleep episode, which can be the main sleep event (i.e., a night sleep for most people) or a nap."
* #Sleep #snoreIndex "Snore index" "The number of snore events per hour."
* #Sleep #snoreEvent "Snore event" "A data type that represents the loudness, duration of snoring, and the posture during snoring."
* #Sleep #sleepAHI "Sleep ahi" "The number of apnea and hypopnea events recorded per hour of sleep."
* #Sleep #sleepArousalIndex "Sleep arousal index" "The average number of arousals per hour of sleep."
* #Sleep #appleSleepingBreathingDisturbances "Apple sleeping breathing disturbances" "A quantity sample type that measures a nightly breathing disturbances."
* #Sleep #sleepApneaEvent "Sleep apnea event" "A category type that represents sleep apnea event."
* #Mobility "Mobility" ""
* #Mobility #appleWalkingSteadiness "Apple walking steadiness" "A quantity sample type that measures the steadiness of the user's gait."
* #Mobility #appleWalkingSteadinessEvent "Apple walking steadiness event" "A category sample type that records an incident where the user showed a reduced score for their gait's steadiness."
* #Mobility #sixMinuteWalkTestDistance "Six minute walk test distance" "A quantity sample type that stores the distance a user can walk during a six-minute walk test."
* #Mobility #walkingSpeed "Walking speed" "A quantity sample type that measures the user's average speed when walking steadily over flat ground."
* #Mobility #walkingStepLength "Walking step length" "A quantity sample type that measures the average length of the user's step when walking steadily over flat ground."
* #Mobility #walkingAsymmetryPercentage "Walking asymmetry percentage" "A quantity sample type that measures the percentage of steps in which one foot moves at a different speed than the other when walking on flat ground."
* #Mobility #walkingDoubleSupportPercentage "Walking double support percentage" "A quantity sample type that measures the percentage of time when both of the user's feet touch the ground while walking steadily over flat ground."
* #Mobility #stairAscentSpeed "Stair ascent speed" "A quantity sample type measuring the user's speed while climbing a flight of stairs."
* #Mobility #stairDescentSpeed "Stair descent speed" "A quantity sample type measuring the user's speed while descending a flight of stairs."
* #Nutrition "Nutrition" ""
* #Nutrition #dietaryBiotin "Biotin" "A quantity sample type that measures the amount of biotin (vitamin B7) consumed."
* #Nutrition #dietaryCaffeine "Caffeine" "A quantity sample type that measures the amount of caffeine consumed."
* #Nutrition #dietaryCalcium "Calcium" "A quantity sample type that measures the amount of calcium consumed."
* #Nutrition #dietaryCarbohydrates "Carbohydrates" "A quantity sample type that measures the amount of carbohydrates consumed."
* #Nutrition #dietaryChloride "Chloride" "A quantity sample type that measures the amount of chloride consumed."
* #Nutrition #dietaryCholesterol "Cholesterol" "A quantity sample type that measures the amount of cholesterol consumed."
* #Nutrition #dietaryChromium "Chromium" "A quantity sample type that measures the amount of chromium consumed."
* #Nutrition #dietaryCopper "Copper" "A quantity sample type that measures the amount of copper consumed."
* #Nutrition #dietaryEnergyConsumed "Energy consumed" "A quantity sample type that measures the amount of energy consumed."
* #Nutrition #dietaryEnergyFromFat "Energy from fat" "A quantity sample type that measures the amount of energy form fat."
* #Nutrition #dietaryFatMonounsaturated "Fat monounsaturated" "A quantity sample type that measures the amount of monounsaturated fat consumed."
* #Nutrition #dietaryFatPolyunsaturated "Fat polyunsaturated" "A quantity sample type that measures the amount of polyunsaturated fat consumed."
* #Nutrition #dietaryFatUnsaturated "Fat unsaturated" "A quantity sample type that measures the amount of unsaturated fat consumed."
* #Nutrition #dietaryTransFat "Trans fat" "A quantity sample type that measures the amount of trans fat consumed."
* #Nutrition #dietaryFatSaturated "Fat saturated" "A quantity sample type that measures the amount of saturated fat consumed."
* #Nutrition #dietaryFatTotal "Fat total" "A quantity sample type that measures the total amount of fat consumed."
* #Nutrition #dietaryFiber "Fiber" "A quantity sample type that measures the amount of fiber consumed."
* #Nutrition #dietaryFolateOrFolicAcid "Folate or folic acid" "A quantity sample type that measures the amount of folate (folic acid) consumed."
* #Nutrition #dietaryFolate "Folate" "A quantity sample type that measures the amount of folate consumed."
* #Nutrition #dietaryFolicAcid "Folic acid" "A quantity sample type that measures the amount of folic acid consumed."
* #Nutrition #dietaryIodine "Iodine" "A quantity sample type that measures the amount of iodine consumed."
* #Nutrition #dietaryIron "Iron" "A quantity sample type that measures the amount of iron consumed."
* #Nutrition #dietaryMagnesium "Magnesium" "A quantity sample type that measures the amount of magnesium consumed."
* #Nutrition #dietaryManganese "Manganese" "A quantity sample type that measures the amount of manganese consumed."
* #Nutrition #dietaryMolybdenum "Molybdenum" "A quantity sample type that measures the amount of molybdenum consumed."
* #Nutrition #dietaryNiacin "Niacin" "A quantity sample type that measures the amount of niacin (vitamin B3) consumed."
* #Nutrition #dietaryPantothenicAcid "Pantothenic acid" "A quantity sample type that measures the amount of pantothenic acid (vitamin B5) consumed."
* #Nutrition #dietaryPhosphorus "Phosphorus" "A quantity sample type that measures the amount of phosphorus consumed."
* #Nutrition #dietaryPotassium "Potassium" "A quantity sample type that measures the amount of potassium consumed."
* #Nutrition #dietaryProtein "Protein" "A quantity sample type that measures the amount of protein consumed."
* #Nutrition #dietaryRiboflavin "Riboflavin" "A quantity sample type that measures the amount of riboflavin (vitamin B2) consumed."
* #Nutrition #dietarySelenium "Selenium" "A quantity sample type that measures the amount of selenium consumed."
* #Nutrition #dietarySodium "Sodium" "A quantity sample type that measures the amount of sodium consumed."
* #Nutrition #dietarySugar "Sugar" "A quantity sample type that measures the amount of sugar consumed."
* #Nutrition #dietaryThiamin "Thiamin" "A quantity sample type that measures the amount of thiamin (vitamin B1) consumed."
* #Nutrition #dietaryVitaminA "Vitamin a" "A quantity sample type that measures the amount of vitamin A consumed."
* #Nutrition #dietaryVitaminB12 "Dietary vitamin b12" "A quantity sample type that measures the amount of cyanocobalamin (vitamin B12) consumed."
* #Nutrition #dietaryVitaminB6 "Vitamin b6" "A quantity sample type that measures the amount of pyridoxine (vitamin B6) consumed."
* #Nutrition #dietaryVitaminC "Vitamin c" "A quantity sample type that measures the amount of vitamin C consumed."
* #Nutrition #dietaryVitaminD "Vitamin d" "A quantity sample type that measures the amount of vitamin D consumed."
* #Nutrition #dietaryVitaminE "Vitamin e" "A quantity sample type that measures the amount of vitamin E consumed."
* #Nutrition #dietaryVitaminK "Vitamin k" "A quantity sample type that measures the amount of vitamin K consumed."
* #Nutrition #dietaryWater "Water" "A quantity sample type that measures the amount of water consumed."
* #Nutrition #dietaryZinc "Zinc" "A quantity sample type that measures the amount of zinc consumed."
* #ReproductiveHealth "Reproductive health" ""
* #ReproductiveHealth #basalBodyTemperature "Basal body temperature" "A quantity sample type that records the user's basal body temperature."
* #ReproductiveHealth #cervicalMucusQuality "Cervical mucus quality" "A category sample type that records the quality of the user's cervical mucus."
* #ReproductiveHealth #contraceptive "Contraceptive" "A category sample type that records the use of contraceptives."
* #ReproductiveHealth #intermenstrualBleeding "Intermenstrual bleeding" "A category sample type that records spotting outside the normal menstruation period."
* #ReproductiveHealth #irregularMenstrualCycles "Irregular menstrual cycles" "A category sample that indicates an irregular menstrual cycle."
* #ReproductiveHealth #infrequentMenstrualCycles "Infrequent menstrual cycles" "A category sample that indicates an infrequent menstrual cycle."
* #ReproductiveHealth #lactation "Lactation" "A category type that records lactation."
* #ReproductiveHealth #menstrualFlow "Menstrual flow" "A category sample type that records menstrual cycles."
* #ReproductiveHealth #menstrualPeriod "Menstrual period" "A category sample type that records menstrual periods."
* #ReproductiveHealth #ovulationTestResult "Ovulation test result" "A category sample type that records the result of an ovulation home test."
* #ReproductiveHealth #persistentIntermenstrualBleeding "Persistent intermenstrual bleeding" "A category sample that indicates persistent intermenstrual bleeding."
* #ReproductiveHealth #pregnancy "Pregnancy" "A category type that records pregnancy."
* #ReproductiveHealth #pregnancyTestResult "Pregnancy test result" "A category type that represents the results from a home pregnancy test."
* #ReproductiveHealth #progesteroneTestResult "Progesterone test result" "A category type that represents the results from a home progesterone test."
* #ReproductiveHealth #prolongedMenstrualPeriods "Prolonged menstrual periods" "A category sample that indicates a prolonged menstrual cycle."
* #ReproductiveHealth #sexualActivity "Sexual activity" "A category sample type that records sexual activity."
* #ReproductiveHealth #bleedingAfterPregnancy "Bleeding after pregnancy" "A category type that represents bleeding after pregnancy."
* #ReproductiveHealth #bleedingDuringPregnancy "Bleeding during pregnancy" "A category type that represents bleeding during pregnancy."
* #SelfCare "Self care" ""
* #SelfCare #handwashingEvent "Handwashing event" "A category sample type for handwashing events."
* #SelfCare #toothbrushingEvent "Toothbrushing event" "A category sample type for toothbrushing events."
* #Symptom "Symptom" ""
* #Symptom #abdominalCramps "Bdominal cramps" "A category type that records abdominal cramps as a symptom."
* #Symptom #acne "Acne" "A category type that records acne as a symptom."
* #Symptom #appetiteChanges "Appetite changes" "A category type that records changes in appetite as a symptom."
* #Symptom #bladderIncontinence "Bladder incontinence" "A category type that records bladder incontinence as a symptom."
* #Symptom #bloating "Bloating" "A category type that records bloating as a symptom."
* #Symptom #breastPain "Breast pain" "A category type that records breast pain as a symptom."
* #Symptom #chestTightnessOrPain "Chest tightness or pain" "A category type that records chest tightness or pain as a symptom."
* #Symptom #chills "Chills" "A category type that records chills as a symptom."
* #Symptom #constipation "Constipation" "A category type that records constipation as a symptom."
* #Symptom #coughing "Coughing" "A category type that records coughing as a symptom."
* #Symptom #diarrhea "Diarrhea" "A category type that records diarrhea as a symptom."
* #Symptom #dizziness "Dizziness" "A category type that records dizziness as a symptom."
* #Symptom #drySkin "Dry skin" "A category type that records dry skin as a symptom."
* #Symptom #fainting "Fainting" "A category type that records fainting as a symptom."
* #Symptom #fatigue "Fatigue" "A category type that records fatigue as a symptom."
* #Symptom #fever "Fever" "A category type that records fever as a symptom."
* #Symptom #generalizedBodyAche "Generalized body ache" "A category type that records body ache as a symptom."
* #Symptom #hairLoss "Hair loss" "A category type that records hair loss as a symptom."
* #Symptom #headache "Headache" "A category type that records headache as a symptom."
* #Symptom #heartburn "Heartburn" "A category type that records heartburn as a symptom."
* #Symptom #hotFlashes "Hot flashes" "A category type that records hot flashes as a symptom."
* #Symptom #lossOfSmell "Loss of smell" "A category type that records loss of smell as a symptom."
* #Symptom #lossOfTaste "Loss of taste" "A category type that records loss of taste as a symptom."
* #Symptom #lowerBackPain "Lower back pain" "A category type that records lower back pain as a symptom."
* #Symptom #memoryLapse "Memory lapse" "A category type that records memory lapse as a symptom."
* #Symptom #moodChanges "Mood changes" "A category type that records mood changes as a symptom."
* #Symptom #nausea "Nausea" "A category type that records nausea as a symptom."
* #Symptom #nightSweats "Night sweats" "A category type that records night sweats as a symptom."
* #Symptom #pelvicPain "Pelvic pain" "A category type that records pelvic pain as a symptom."
* #Symptom #rapidPoundingOrFlutteringHeartbeat "Rapid pounding or fluttering heartbeat" "A category type that records a rapid,  pounding,  or fluttering heartbeat as a symptom."
* #Symptom #runnyNose "Runny nose" "A category type that records runny nose as a symptom."
* #Symptom #shortnessOfBreath "Shortness of breath" "A category type that records shortness of breath as a symptom."
* #Symptom #sinusCongestion "Sinus congestion" "A category type that records sinus congestion as a symptom."
* #Symptom #skippedHeartbeat "Skipped heartbeat" "A category type that records skipped heartbeat as a symptom."
* #Symptom #sleepChanges "Sleep changes" "A category type that records sleep changes as a symptom."
* #Symptom #soreThroat "Sore throat" "A category type that records sore throat as a symptom."
* #Symptom #vaginalDryness "Vaginal dryness" "A category type that records vaginal dryness as a symptom."
* #Symptom #vomiting "Vomiting" "A category type that records vomiting as a symptom."
* #Symptom #wheezing "Wheezing" "A category type that records wheezing as a symptom."
* #UVExposure "Uv exposure" ""
* #UVExposure #uvExposure "Uv exposure" "A quantity sample type that measures the user's exposure to UV radiation."
* #VitalSigns "Vital signs" ""
* #VitalSigns #atrialFibrillationBurden "Atrial fibrillation burden" "A quantity type that measures an estimate of the percentage of time a person's heart shows signs of atrial fibrillation (AFib) while wearing Apple Watch."
* #VitalSigns #bloodPressure "Blood pressure" "A correlation sample that combines a systolic sample and a diastolic sample into a single blood pressure reading."
* #VitalSigns #bloodPressureDiastolic "Blood pressure diastolic" "A quantity sample type that measures the user's diastolic blood pressure."
* #VitalSigns #bloodPressureSystolic "Blood pressure systolic" "A quantity sample type that measures the user's systolic blood pressure."
* #VitalSigns #bodyTemperature "Body temperature" "A quantity sample type that measures the user's body temperature."
* #VitalSigns #heartRate "Heart rate" "A quantity sample type that measures the user's heart rate."
* #VitalSigns #heartRateVariabilitySDNN "Heart rate variability sdnn" "A quantity sample type that measures the standard deviation of heartbeat intervals."
* #VitalSigns #heartRateRecoveryOneMinute "Heart rate recovery one minute" "A quantity sample that records the reduction in heart rate from the peak exercise rate to the rate one minute after exercising ended."
* #VitalSigns #highHeartRateEvent "High heart rate event" "A category sample type for high heart rate events."
* #VitalSigns #irregularHeartRhythmEvent "Irregular heart rhythm event" "A category sample type for irregular heart rhythm events."
* #VitalSigns #lowHeartRateEvent "Low heart rate event" "A category sample type for low heart rate events."
* #VitalSigns #oxygenSaturation "Oxygen saturation" "A quantity sample type that measures the user's oxygen saturation."
* #VitalSigns #respiratoryRate "Respiratory rate" "A quantity sample type that measures the user's respiratory rate."
* #VitalSigns #restingHeartRate "Resting heart rate" "A quantity sample type that measures the user's resting heart rate."
* #VitalSigns #walkingHeartRateAverage "Walking heart rate average" "A quantity sample type that measures the user's heart rate while walking."
* #VitalSigns #rrInterval "Rr interval" "The time period between successive R waves."
* #WorkoutActivity "Workout activity" ""
* #WorkoutActivity #americanFootball "American football" "The constant for playing American football."
* #WorkoutActivity #archery "Archery" "The constant for shooting archery."
* #WorkoutActivity #australianFootball "Australian football" "The constant for playing Australian football."
* #WorkoutActivity #badminton "Badminton" "The constant for playing badminton."
* #WorkoutActivity #barre "Barre" "The constant for barre workout."
* #WorkoutActivity #baseball "Baseball" "The constant for playing baseball."
* #WorkoutActivity #basketball "Basketball" "The constant for playing basketball."
* #WorkoutActivity #bowling "Bowling" "The constant for bowling."
* #WorkoutActivity #boxing "Boxing" "The constant for boxing."
* #WorkoutActivity #cardioDance "Cardio dance" "The constant for cardiovascular dance workouts."
* #WorkoutActivity #climbing "Climbing" "The constant for climbing."
* #WorkoutActivity #cooldown "Cooldown" "The constant for low intensity stretching and mobility exercises following a more vigorous workout."
* #WorkoutActivity #coreTraining "Core training" "The constant for core training."
* #WorkoutActivity #cricket "Cricket" "The constant for playing cricket."
* #WorkoutActivity #crossCountrySkiing "Cross country skiing" "The constant for cross country skiing."
* #WorkoutActivity #crossTraining "Cross training" "The constant for exercise that includes any mixture of cardio, strength, and/or flexibility training."
* #WorkoutActivity #curling "Curling" "The constant for curling."
* #WorkoutActivity #cycling "Cycling" "The constant for cycling."
* #WorkoutActivity #dance "Dance" "(Deprecated) The constant for dancing."
* #WorkoutActivity #danceInspiredTraining "Dance inspired training" "(Deprecated) The constant for workouts inspired by dance, including Pilates, Barre, and Feldenkrais."
* #WorkoutActivity #discSports "Disc sports" "The constant for playing disc sports such as Ultimate and Disc Golf."
* #WorkoutActivity #downhillSkiing "Downhill skiing" "The constant for downhill skiing."
* #WorkoutActivity #elliptical "Elliptical" "The constant for workouts on an elliptical machine."
* #WorkoutActivity #equestrianSports "Equestrian sports" "The constant for activities that involve riding a horse, including polo, horse racing, and horse riding."
* #WorkoutActivity #fencing "Fencing" "The constant for fencing."
* #WorkoutActivity #fishing "Fishing" "The constant for fishing."
* #WorkoutActivity #fitnessGaming "Fitness gaming" "The constant for playing fitness-based video games."
* #WorkoutActivity #flexibility "Flexibility" "The constant for a flexibility workout."
* #WorkoutActivity #functionalStrengthTraining "Functional strength training" "The constant for strength training, primarily with free weights and body weight."
* #WorkoutActivity #golf "Golf" "The constant for playing golf."
* #WorkoutActivity #gymnastics "Gymnastics" "Performing gymnastics."
* #WorkoutActivity #handball "Handball" "The constant for playing handball."
* #WorkoutActivity #handCycling "Hand cycling" "The constant for hand cycling."
* #WorkoutActivity #highIntensityIntervalTraining "High intensity interval training" "The constant for high intensity interval training."
* #WorkoutActivity #hiking "Hiking" "The constant for hiking."
* #WorkoutActivity #hockey "Hockey" "The constant for playing hockey, including ice hockey, field hockey, and related sports."
* #WorkoutActivity #hunting "Hunting" "The constant for hunting."
* #WorkoutActivity #jumpRope "Jump rope" "The constant for jumping rope."
* #WorkoutActivity #kickboxing "Kickboxing" "The constant for kickboxing."
* #WorkoutActivity #lacrosse "Lacrosse" "The constant for playing lacrosse."
* #WorkoutActivity #martialArts "Martial arts" "The constant for practicing martial arts."
* #WorkoutActivity #mindAndBody "Mind and body" "The constant for performing activities like walking meditation, Gyrotonic exercise, and Qigong."
* #WorkoutActivity #mixedCardio "Mixed cardio" "The constant for workouts that mix a variety of cardio exercise machines or modalities."
* #WorkoutActivity #mixedMetabolicCardioTraining "Mixed metabolic cardio training" "The constant for performing any mix of cardio-focused exercises."
* #WorkoutActivity #other "Other" "The constant for a workout that does not match any of the other workout activity types."
* #WorkoutActivity #paddleSports "Paddle sports" "The constant for canoeing, kayaking, paddling an outrigger, paddling a stand-up paddle board, and related sports."
* #WorkoutActivity #pickleball "Pickleball" "The constant for playing pickleball."
* #WorkoutActivity #pilates "Pilates" "The constant for a pilates workout."
* #WorkoutActivity #play "Play" "The constant for play-based activities like tag, dodgeball, hopscotch, tetherball, and playing on a jungle gym."
* #WorkoutActivity #preparationAndRecovery "Preparation and recovery" "The constant for warm-up and therapeutic activities like foam rolling and stretching."
* #WorkoutActivity #racquetball "Racquetball" "The constant for playing racquetball."
* #WorkoutActivity #rowing "Rowing" "The constant for rowing."
* #WorkoutActivity #rugby "Rugby" "The constant for playing rugby."
* #WorkoutActivity #running "Running" "The constant for running and jogging."
* #WorkoutActivity #sailing "Sailing" "The constant for sailing."
* #WorkoutActivity #skatingSports "Skating sports" "The constant for skating activities, including ice skating, speed skating, inline skating, and skateboarding."
* #WorkoutActivity #snowboarding "Snowboarding" "The constant for snowboarding."
* #WorkoutActivity #snowSports "Snow sports" "The constant for a variety of snow sports, including sledding, snowmobiling, or building a snowman."
* #WorkoutActivity #soccer "Soccer" "The constant for playing soccer."
* #WorkoutActivity #socialDance "Social dance" "The constant for dancing with a partner or partners, such as swing, salsa, or folk dances."
* #WorkoutActivity #softball "Softball" "The constant for playing softball."
* #WorkoutActivity #squash "Squash" "The constant for playing squash."
* #WorkoutActivity #stairClimbing "Stair climbing" "The constant for workouts using a stair climbing machine."
* #WorkoutActivity #stairs "Stairs" "The constant for running, walking, or other drills using stairs (for example, in a stadium or inside a multilevel building)."
* #WorkoutActivity #stepTraining "Step training" "The constant for training using a step bench."
* #WorkoutActivity #surfingSports "Surfing sports" "The constant for a variety of surf sports, including surfing, kite surfing, and wind surfing."
* #WorkoutActivity #swimBikeRun "Swim bike run" "The constant for multisport activities like triathlons."
* #WorkoutActivity #swimming "Swimming" "The constant for swimming."
* #WorkoutActivity #tableTennis "Table tennis" "The constant for playing table tennis."
* #WorkoutActivity #taiChi "Tai chi" "The constant for tai chi."
* #WorkoutActivity #tennis "Tennis" "The constant for playing tennis."
* #WorkoutActivity #trackAndField "Track and field" "Participating in track and field events, including shot put, javelin, pole vaulting, and related sports."
* #WorkoutActivity #traditionalStrengthTraining "Traditional strength training" "The constant for strength training exercises primarily using machines or free weights."
* #WorkoutActivity #transition "Transition" "A constant for the transition time between activities in a multisport workout."
* #WorkoutActivity #underwaterDiving "Underwater diving" "The constant for underwater diving."
* #WorkoutActivity #volleyball "Volleyball" "The constant for playing volleyball."
* #WorkoutActivity #walking "Walking" "The constant for walking."
* #WorkoutActivity #waterFitness "Water fitness" "The constant for aerobic exercise performed in shallow water."
* #WorkoutActivity #waterPolo "Water polo" "The constant for playing water polo."
* #WorkoutActivity #waterSports "Water sports" "The constant for a variety of water sports, including water skiing, wake boarding, and related activities."
* #WorkoutActivity #wheelchairRunPace "Wheelchair run pace" "The constant for wheelchair workout at running pace."
* #WorkoutActivity #wheelchairWalkPace "Wheelchair walk pace" "The constant for a wheelchair workout at walking pace."
* #WorkoutActivity #wrestling "Wrestling" "The constant for wrestling."
* #WorkoutActivity #yoga "Yoga" "The constant for practicing yoga."
* #WorkoutActivity #backExtension "Back extension" "The constant for back Extension."
* #WorkoutActivity #barbellShoulderPress "Barbell shoulder press" "The constant for barbell shoulder press."
* #WorkoutActivity #benchPress "Bench press" "The constant for bench press."
* #WorkoutActivity #benchSitUp "Bench sit up" "The constant for bench sit up."
* #WorkoutActivity #biking "Biking" "The constant for biking."
* #WorkoutActivity #bikingStationary "Biking stationary" "The constant for biking stationary."
* #WorkoutActivity #bootCamp "Boot camp" "The constant for boot camp."
* #WorkoutActivity #burpee "Burpee" "The constant for burpee."
* #WorkoutActivity #calisthenics "Calisthenics" "The constant for calisthenics."
* #WorkoutActivity #crunch "Crunch" "The constant for crunch."
* #WorkoutActivity #deadlift "Deadlift" "The constant for deadlift."
* #WorkoutActivity #dumbbellCurlLeftArm "Dumbbell curl left arm" "The constant for dumbbell curl left arm."
* #WorkoutActivity #dumbbellCurlRightArm "Dumbbell curl right arm" "The constant for dumbbell curl right arm."
* #WorkoutActivity #dumbbellFrontRaise "Dumbbell front raise" "The constant for dumbbell front raise."
* #WorkoutActivity #dumbbellLateralRaise "Dumbbell lateral raise" "The constant for dumbbell lateral raise."
* #WorkoutActivity #dumbbellTricepsExtensionLeftArm "Dumbbell triceps extension left arm" "The constant for dumbbell triceps extension left arm."
* #WorkoutActivity #dumbbellTricepsExtensionRightArm "Dumbbell triceps extension right arm" "The constant for dumbbell triceps extension right arm."
* #WorkoutActivity #dumbbellTricepsExtensionTwoArm "Dumbbell triceps extension two arm" "The constant for dumbbell triceps extension two arm."
* #WorkoutActivity #exerciseClass "Exercise class" "The constant for exercise class."
* #WorkoutActivity #forwardTwist "Forward twist" "The constant for forward twist."
* #WorkoutActivity #frisbeeDisc "Frisbee disc" "The constant for frisbee disc."
* #WorkoutActivity #guidedBreathing "Guided breathing" "The constant for guided breathing."
* #WorkoutActivity #iceHockey "Ice hockey" "The constant for ice hockey."
* #WorkoutActivity #iceSkating "Ice skating" "The constant for ice skating."
* #WorkoutActivity #jumpingJack "Jumping jack" "The constant for jumping jack."
* #WorkoutActivity #latPullDown "Lat pull down" "The constant for lat pull down."
* #WorkoutActivity #lunge "Lunge" "The constant for lunge."
* #WorkoutActivity #meditation "Meditation" "The constant for meditation."
* #WorkoutActivity #paraGliding "Para gliding" "The constant for para gliding."
* #WorkoutActivity #plank "Plank" "The constant for plank."
* #WorkoutActivity #rockClimbing "Rock climbing" "The constant for rock climbing."
* #WorkoutActivity #rollerHockey "Roller hockey" "The constant for roller hockey."
* #WorkoutActivity #rowingMachine "Rowing machine" "The constant for rowing machine."
* #WorkoutActivity #runningTreadmill "Running treadmill" "The constant for running treadmill."
* #WorkoutActivity #scubaDiving "Scuba diving" "The constant for scuba diving."
* #WorkoutActivity #skiing "Skiing" "The constant for skiing."
* #WorkoutActivity #snowshoeing "Snowshoeing" "The constant for snowshoeing."
* #WorkoutActivity #squat "Squat" "The constant for squat."
* #WorkoutActivity #strengthTraining "Strength training" "The constant for strength training."
* #WorkoutActivity #stretching "Stretching" "The constant for stretching."
* #WorkoutActivity #swimmingOpenWater "Swimming open water" "The constant for swimming open water."
* #WorkoutActivity #swimmingPool "Swimming pool" "The constant for swimming pool."
* #WorkoutActivity #upperTwist "Upper twist" "The constant for upper twist."
* #WorkoutActivity #weightlifting "Weightlifting" "The constant for weightlifting."
* #WorkoutActivity #wheelchair "Wheelchair" "The constant for wheelchair."
* #WorkoutActivity #workout "Workout" "The constant for workout."
* #WorkoutActivity #armCurl "Arm curl" "The constant for arm curl exercises targeting the biceps."
* #WorkoutActivity #ballSlam "Ball slam" "The constant for full-body workouts using a slam ball."
* #WorkoutActivity #doubleArmTricepsExtension "Double arm triceps extension" "The constant for triceps extension exercises using both arms."
* #WorkoutActivity #dumbbellRow "Dumbbell row" "The constant for back-strengthening exercises using dumbbells."
* #WorkoutActivity #frontRaise "Front raise" "The constant for shoulder workouts lifting weights in front of the body."
* #WorkoutActivity #hipThrust "Hip thrust" "The constant for glute-focused exercises involving hip elevation."
* #WorkoutActivity #hulaHoop "Hula hoop" "The constant for core and cardio workouts using a hula hoop."
* #WorkoutActivity #kettlebellSwing "Kettlebell swing" "The constant for dynamic full-body workouts using a kettlebell."
* #WorkoutActivity #lateralRaise "Lateral raise" "The constant for shoulder workouts lifting weights to the sides."
* #WorkoutActivity #legCurl "Leg curl" "The constant for hamstring-focused leg curl exercises."
* #WorkoutActivity #legExtension "Leg extension" "The constant for quadriceps-focused leg extension exercises."
* #WorkoutActivity #legPress "Leg press" "The constant for lower-body strength training using a leg press machine."
* #WorkoutActivity #legRaise "Leg raise" "The constant for abdominal and hip flexor exercises involving leg lifts."
* #WorkoutActivity #mountainClimber "Mountain climber" "The constant for cardio and core workouts simulating climbing motion."
* #WorkoutActivity #otherWorkout "Other workout" "The constant for workouts not categorized under specific types."
* #WorkoutActivity #pause "Pause" "The constant for temporary pauses during a workout session."
* #WorkoutActivity #pullUp "Pull-up" "The constant for upper-body strength exercises involving pulling up the body."
* #WorkoutActivity #punch "Punch" "The constant for boxing-style workouts involving punching motions."
* #WorkoutActivity #rest "Rest" "The constant for rest periods between or after workouts."
* #WorkoutActivity #shoulderPress "Shoulder press" "The constant for overhead pressing exercises targeting the shoulders."
* #WorkoutActivity #singleArmTricepsExtension "Single arm triceps extension" "The constant for triceps extension exercises using one arm."
* #WorkoutActivity #sitUp "Sit-up" "The constant for abdominal exercises involving torso lifts."
* #WorkoutActivity #stairClimbingMachine "Stair climbing" "The constant for workouts using a stair climbing machine."
* #WorkoutActivity #swimmingBackstroke "Swimming backstroke" "The constant for swimming using the backstroke technique."
* #WorkoutActivity #swimmingBreaststroke "Swimming breaststroke" "The constant for swimming using the breaststroke technique."
* #WorkoutActivity #swimmingButterfly "Swimming butterfly" "The constant for swimming using the butterfly stroke."
* #WorkoutActivity #swimmingFreestyle "Swimming freestyle" "The constant for swimming using the freestyle stroke."
* #WorkoutActivity #swimmingMixed "Swimming mixed" "The constant for swimming using a combination of strokes."
* #WorkoutActivity #swimmingOther "Swimming other" "The constant for swimming using other or unspecified techniques."
* #Audiogram "Audiogram" ""
* #Audiogram #hearingSensitivity "Hearing sensitivity" "A pair of frequencies and left/right ear sensitivity data to represent the patient's hearing sensitivity for each frequency."
* #food "Food" ""
* #medicationAdherence "Medication adherence" "The degree to which a patient correctly follows medical advice, particularly in relation to taking prescribed medication."
* #Mind "Mind" ""
* #Mind #stateOfMind "State of Mind" "Momentary emotions and daily moods."
* #Mind #gad7 "GAD-7 assessment" "The Generalized Anxiety Disorder 7-item scale."
* #Mind #phq9 "PHQ-9 assessment" "The nine-item Patient Health Questionnaire."

//Unit
* insert UnitRules(#Activity #distanceWalkingRunning, #km)
* insert UnitRules(#Activity #runningGroundContactTime, #s)
* insert UnitRules(#Activity #runningPower, #W)
* insert UnitRules(#Activity #runningSpeed, #m/s)
* insert UnitRules(#Activity #runningStrideLength, #m)
* insert UnitRules(#Activity #runningVerticalOscillation, #m)
* insert UnitRules(#Activity #distanceCycling, #m)
* insert UnitRules(#Activity #distanceWheelchair, #m)
* insert UnitRules(#Activity #distanceSwimming, #m)
* insert UnitRules(#Activity #distanceDownhillSnowSports, #m)
* insert UnitRules(#Activity #basalEnergyBurned, #kcal)
* insert UnitRules(#Activity #activeEnergyBurned, #kcal)
* insert UnitRules(#Activity #totalEnergyBurned, #kcal)
* insert UnitRules(#Activity #elevationGained, #m)
* insert UnitRules(#Activity #appleExerciseTime, #min)
* insert UnitRules(#Activity #appleMoveTime, #min)
* insert UnitRules(#Activity #appleStandTime, #min)
* insert UnitRules(#Activity #vo2Max, #ml/kg/min)
* insert UnitRules(#Activity #cyclingFunctionalThresholdPower, #W)
* insert UnitRules(#Activity #cyclingPower, #W)
* insert UnitRules(#Activity #cyclingSpeed, #km/h)
* insert UnitRules(#Activity #distance, #m)
* insert UnitRules(#Activity #power, #W)
* insert UnitRules(#Activity #physicalEffort, #kcal/(kg.h\))
* insert UnitRules(#Activity #speed, #m/s)
* insert UnitRules(#Activity #pace, #min/km)

* insert UnitRules(#Activity #crossCountrySkiingSpeed, #km/h)
* insert UnitRules(#Activity #distanceCrossCountrySkiing, #km)
* insert UnitRules(#Activity #paddleSportsSpeed, #km/h)
* insert UnitRules(#Activity #distancePaddleSports, #km)
* insert UnitRules(#Activity #rowingSpeed, #km/h)
* insert UnitRules(#Activity #distanceRowing, #km)
* insert UnitRules(#Activity #distanceSkatingSports, #km)

* insert UnitRules(#Diving #underwaterDepth, #m)
* insert UnitRules(#Diving #waterTemperature, #Cel)
* insert UnitRules(#AlcoholConsumption #bloodAlcoholContent, #%)

* insert UnitRules(#BodyMeasurements #appleSleepingWristTemperature, #Cel)
* insert UnitRules(#BodyMeasurements #height, #cm)
* insert UnitRules(#BodyMeasurements #bodyMass, #kg)
* insert UnitRules(#BodyMeasurements #leanBodyMass, #kg)
* insert UnitRules(#BodyMeasurements #bodyFatPercentage, #%)
* insert UnitRules(#BodyMeasurements #waistCircumference, #cm)
* insert UnitRules(#BodyMeasurements #hipCircumference, #cm)
* insert UnitRules(#BodyMeasurements #boneMass, #kg)
* insert UnitRules(#Hearing #environmentalAudioExposure, #dB)
* insert UnitRules(#Hearing #environmentalSoundReduction, #dB)
* insert UnitRules(#Hearing #headphoneAudioExposure, #dB)
* insert UnitRules(#VitalSigns #atrialFibrillationBurden, #%)
* insert UnitRules(#VitalSigns #heartRate, #/min)
* insert UnitRules(#VitalSigns #restingHeartRate, #/min)
* insert UnitRules(#VitalSigns #walkingHeartRateAverage, #/min)
* insert UnitRules(#VitalSigns #heartRateVariabilitySDNN, #ms)
* insert UnitRules(#VitalSigns #heartRateRecoveryOneMinute, #/min)
* insert UnitRules(#VitalSigns #oxygenSaturation, #%)
* insert UnitRules(#VitalSigns #bodyTemperature, #Cel)
* insert UnitRules(#VitalSigns #bloodPressureDiastolic, #mm[Hg])
* insert UnitRules(#VitalSigns #bloodPressureSystolic, #mm[Hg])
* insert UnitRules(#VitalSigns #respiratoryRate, #/min)
* insert UnitRules(#VitalSigns #rrInterval, #ms)
* insert UnitRules(#LabAndTestResults #bloodGlucose, #mmol/L)
* insert UnitRules(#LabAndTestResults #electrodermalActivity, #S)
* insert UnitRules(#LabAndTestResults #forcedExpiratoryVolume1, #L)
* insert UnitRules(#LabAndTestResults #forcedVitalCapacity, #L)
* insert UnitRules(#LabAndTestResults #insulinDelivery, #[IU])
* insert UnitRules(#LabAndTestResults #peakExpiratoryFlowRate, #L/min)
* insert UnitRules(#LabAndTestResults #peripheralPerfusionIndex, #%)
* insert UnitRules(#LabAndTestResults #timeInDaylight, #min)
* insert UnitRules(#LabAndTestResults #inspiratoryTime, #s)
* insert UnitRules(#LabAndTestResults #ventilationCycleTime, #s)
* insert UnitRules(#LabAndTestResults #minuteVolume, #mL/min)
* insert UnitRules(#LabAndTestResults #breathCarbonMonoxide, #[ppm])
* insert UnitRules(#Sleep #sleepAHI, #/h)
* insert UnitRules(#Sleep #sleepArousalIndex, #/h)
* insert UnitRules(#Mobility #appleWalkingSteadiness, #%)
* insert UnitRules(#Mobility #sixMinuteWalkTestDistance, #m/(6.min\))
* insert UnitRules(#Mobility #walkingSpeed, #m/s)
* insert UnitRules(#Mobility #walkingStepLength, #m)
* insert UnitRules(#Mobility #walkingAsymmetryPercentage, #%)
* insert UnitRules(#Mobility #walkingDoubleSupportPercentage, #%)
* insert UnitRules(#Mobility #stairAscentSpeed, #m/s)
* insert UnitRules(#Mobility #stairDescentSpeed, #m/s)
* insert UnitRules(#Nutrition #dietaryBiotin, #ug)
* insert UnitRules(#Nutrition #dietaryCaffeine, #mg)
* insert UnitRules(#Nutrition #dietaryCalcium, #mg)
* insert UnitRules(#Nutrition #dietaryCarbohydrates, #g)
* insert UnitRules(#Nutrition #dietaryChloride, #g)
* insert UnitRules(#Nutrition #dietaryCholesterol, #mg)
* insert UnitRules(#Nutrition #dietaryChromium, #ug)
* insert UnitRules(#Nutrition #dietaryCopper, #mg)
* insert UnitRules(#Nutrition #dietaryEnergyConsumed, #kcal)
* insert UnitRules(#Nutrition #dietaryEnergyFromFat, #kcal)
* insert UnitRules(#Nutrition #dietaryFatMonounsaturated, #g)
* insert UnitRules(#Nutrition #dietaryFatPolyunsaturated, #g)
* insert UnitRules(#Nutrition #dietaryFatUnsaturated, #g)
* insert UnitRules(#Nutrition #dietaryTransFat, #g)
* insert UnitRules(#Nutrition #dietaryFatSaturated, #g)
* insert UnitRules(#Nutrition #dietaryFatTotal, #g)
* insert UnitRules(#Nutrition #dietaryFiber, #g)
* insert UnitRules(#Nutrition #dietaryFolateOrFolicAcid, #ug)
* insert UnitRules(#Nutrition #dietaryFolate, #ug)
* insert UnitRules(#Nutrition #dietaryFolicAcid, #ug)
* insert UnitRules(#Nutrition #dietaryIodine, #ug)
* insert UnitRules(#Nutrition #dietaryIron, #mg)
* insert UnitRules(#Nutrition #dietaryMagnesium, #mg)
* insert UnitRules(#Nutrition #dietaryManganese, #mg)
* insert UnitRules(#Nutrition #dietaryMolybdenum, #ug)
* insert UnitRules(#Nutrition #dietaryNiacin, #mg)
* insert UnitRules(#Nutrition #dietaryPantothenicAcid, #mg)
* insert UnitRules(#Nutrition #dietaryPhosphorus, #mg)
* insert UnitRules(#Nutrition #dietaryPotassium, #mg)
* insert UnitRules(#Nutrition #dietaryProtein, #g)
* insert UnitRules(#Nutrition #dietaryRiboflavin, #mg)
* insert UnitRules(#Nutrition #dietarySelenium, #ug)
* insert UnitRules(#Nutrition #dietarySodium, #mg)
* insert UnitRules(#Nutrition #dietarySugar, #g)
* insert UnitRules(#Nutrition #dietaryThiamin, #mg)
* insert UnitRules(#Nutrition #dietaryVitaminA, #ug)
* insert UnitRules(#Nutrition #dietaryVitaminB12, #ug)
* insert UnitRules(#Nutrition #dietaryVitaminB6, #mg)
* insert UnitRules(#Nutrition #dietaryVitaminC, #mg)
* insert UnitRules(#Nutrition #dietaryVitaminD, #ug)
* insert UnitRules(#Nutrition #dietaryVitaminE, #mg)
* insert UnitRules(#Nutrition #dietaryVitaminK, #ug)
* insert UnitRules(#Nutrition #dietaryWater, #L)
* insert UnitRules(#Nutrition #dietaryZinc, #mg)
* insert UnitRules(#ReproductiveHealth #basalBodyTemperature, #Cel)
